namespace Collectibles.Infrastructure.Persistence.Seeders;

public static class VintageComputerTagSeeder
{
    public static async Task SeedTagsAsync(ApplicationDbContext context)
    {
        // Check if tags already exist
        if (await context.Tags.AnyAsync())
        {
            return;
        }

        var tags = GetVintageComputerTags();

        foreach (var tagName in tags)
        {
            var tag = new Tag
            {
                Name = tagName
            };
            context.Tags.Add(tag);
        }

        await context.SaveChangesAsync();
    }

    private static List<string> GetVintageComputerTags()
    {
        var tags = new List<string>();

        // Manufacturers - Major Brands
        tags.AddRange(new[]
        {
            "Apple", "Commodore", "IBM", "Atari", "Tandy", "Radio Shack", "Sinclair", "Amstrad",
            "Acorn", "BBC", "Texas Instruments", "Compaq", "Dell", "Gateway", "Packard Bell",
            "HP", "Hewlett-Packard", "DEC", "Digital Equipment Corporation", "Sun Microsystems",
            "Silicon Graphics", "SGI", "NeXT", "Be Inc", "Olivetti", "Philips", "Sharp", "NEC",
            "Fujitsu", "Hitachi", "Toshiba", "Sony", "Panasonic", "Sanyo", "Epson", "Canon",
            "Mitsubishi", "Casio", "Sega", "Nintendo", "MSX", "Spectravideo", "Dragon Data",
            "Oric", "Thomson", "Schneider", "Grundig", "Robotron", "Pravetz", "Tesla",
            "Wang", "Zenith", "Kaypro", "Osborne", "Morrow", "Eagle", "Franklin", "Laser",
            "VTech", "Video Technology", "Leading Edge", "AST", "Acer", "Everex", "Hyundai",
            "Daewoo", "Samsung", "LG", "GoldStar", "TriGem", "Viglen", "Apricot", "ACT",
            "Research Machines", "Torch", "Camputers", "Jupiter Cantab", "Memotech", "Tatung",
            "Einstein", "Mattel", "Coleco", "Timex", "Exidy", "Micro-Professor", "Multitech",
            "Amdek", "BMC", "Corona", "Columbia", "Eagle Computer", "Mindset", "Visual",
            "Grid", "GRiD Systems", "Gavilan", "Poqet", "Psion", "Tandon", "Tulip", "ICL",
            "Siemens", "Nixdorf", "Bull", "Groupe Bull", "CII", "Honeywell", "Control Data",
            "CDC", "Cray", "Data General", "Prime Computer", "Perkin Elmer", "Burroughs",
            "Sperry", "UNIVAC", "NCR", "AT&T", "Western Digital", "Northgate", "Zeos",
            "Micron", "ALR", "Advanced Logic Research", "DTK", "PC's Limited", "Swan",
            "Victor", "Sirius", "Apricot Computers", "Cromemco", "IMSAI", "MITS", "Altair",
            "Processor Technology", "North Star", "Vector Graphic", "CompuPro", "S-100",
            "Heath", "Heathkit", "SWTPC", "Southwest Technical Products", "Ohio Scientific",
            "Smoke Signal Broadcasting", "Netronics", "Interact", "Exidy Sorcerer", "APF",
            "Bally", "Magnavox", "Fairchild", "RCA", "GE", "General Electric", "Xerox",
            "Symbolics", "Lisp Machines Inc", "LMI", "Thinking Machines", "Connection Machine",
            "MasPar", "Kendall Square Research", "Convex", "Alliant", "Encore", "Sequent",
            "Pyramid Technology", "Ridge Computers", "Convergent Technologies", "Fortune Systems",
            "Altos", "Molecular Computer", "Plexus", "Dual Systems", "Onyx", "Zilog", "Tandem",
            "Stratus", "Tolerant Systems", "Apollo Computer", "Intergraph", "Evans & Sutherland",
            "Megatek", "Ramtek", "Tektronix", "Lexidata", "Adage", "Aydin", "Genisco",
            "Sanders Associates", "Lundy", "Information Displays Inc", "IDI", "Chromatics",
            "Number Nine", "Matrox", "Artist Graphics", "Hercules", "Paradise", "STB",
            "Diamond", "Cirrus Logic", "S3", "3dfx", "ATI", "Nvidia", "Rendition", "3Dlabs",
            "Creative Labs", "Voodoo Graphics", "PowerVR", "Kyro", "Orchid", "Canopus",
            "ELSA", "Gainward", "Sparkle", "PNY", "EVGA", "XFX", "Sapphire", "HIS", "VisionTek",
            "Jaton", "Pine", "Biostar", "Chaintech", "ECS", "Elite", "FIC", "First International",
            "Gigabyte", "Jetway", "MSI", "Micro-Star", "PC Chips", "QDI", "Shuttle", "Soyo",
            "Supermicro", "Tyan", "VIA", "Zida", "Abit", "Aopen", "ASUS", "ASRock", "DFI",
            "EPoX", "Foxconn", "Intel", "J&W", "Leadtek", "Lite-On", "Palit", "PC Partner",
            "Pegatron", "Point of View", "POV", "Powercolor", "Transcend", "XGI", "SiS"
        });

        // Computer Models - Apple
        tags.AddRange(new[]
        {
            "Apple I", "Apple II", "Apple II Plus", "Apple IIe", "Apple IIc", "Apple IIc Plus",
            "Apple IIGS", "Apple III", "Apple Lisa", "Lisa 2", "Macintosh XL", "Macintosh 128K",
            "Macintosh 512K", "Macintosh Plus", "Macintosh SE", "Macintosh SE/30", "Macintosh Classic",
            "Macintosh Classic II", "Macintosh Color Classic", "Macintosh LC", "Macintosh LC II",
            "Macintosh LC III", "Macintosh II", "Macintosh IIx", "Macintosh IIcx", "Macintosh IIci",
            "Macintosh IIfx", "Macintosh IIsi", "Macintosh IIvi", "Macintosh IIvx", "Macintosh Quadra",
            "Quadra 605", "Quadra 610", "Quadra 650", "Quadra 700", "Quadra 800", "Quadra 840AV",
            "Quadra 900", "Quadra 950", "Macintosh Centris", "Centris 610", "Centris 650", "Centris 660AV",
            "Macintosh Performa", "Performa 200", "Performa 400", "Performa 450", "Performa 460",
            "Performa 475", "Performa 476", "Performa 550", "Performa 575", "Performa 600", "Performa 630",
            "Power Macintosh", "Power Mac 6100", "Power Mac 7100", "Power Mac 8100", "Power Mac 7200",
            "Power Mac 7300", "Power Mac 7500", "Power Mac 7600", "Power Mac 8500", "Power Mac 8600",
            "Power Mac 9500", "Power Mac 9600", "Power Mac G3", "Power Mac G4", "Power Mac G4 Cube",
            "Power Mac G5", "iMac G3", "iMac G4", "iMac G5", "eMac", "Mac Mini G4", "PowerBook",
            "PowerBook 100", "PowerBook 140", "PowerBook 145", "PowerBook 150", "PowerBook 160",
            "PowerBook 165", "PowerBook 170", "PowerBook 180", "PowerBook Duo", "Duo 210", "Duo 230",
            "Duo 250", "Duo 270c", "Duo 280", "Duo 280c", "PowerBook 190", "PowerBook 500", "PowerBook 520",
            "PowerBook 540", "PowerBook 1400", "PowerBook 2400", "PowerBook 3400", "PowerBook G3",
            "PowerBook G4", "iBook", "iBook G3", "iBook G4", "MacBook", "MacBook Pro", "MacBook Air",
            "Newton", "MessagePad", "MessagePad 100", "MessagePad 110", "MessagePad 120", "MessagePad 130",
            "MessagePad 2000", "MessagePad 2100", "eMate 300"
        });

        // Computer Models - Commodore
        tags.AddRange(new[]
        {
            "Commodore PET", "PET 2001", "PET 4032", "PET 8032", "CBM 8032", "SuperPET", "Commodore VIC-20",
            "VIC-1001", "Commodore 64", "C64", "C64C", "C64G", "C64GS", "Commodore SX-64", "Executive 64",
            "Commodore 128", "C128", "C128D", "C128DCR", "Commodore Plus/4", "Commodore 16", "C16",
            "Commodore 116", "Commodore 264", "Commodore MAX", "Ultimax", "Educator 64", "PET 64",
            "Commodore 65", "C65", "Commodore 64DX", "Commodore Amiga", "Amiga 1000", "A1000", "Amiga 500",
            "A500", "A500 Plus", "Amiga 600", "A600", "Amiga 1200", "A1200", "Amiga 2000", "A2000",
            "Amiga 2500", "A2500", "Amiga 3000", "A3000", "A3000T", "A3000UX", "Amiga 4000", "A4000",
            "A4000T", "Amiga CD32", "CDTV", "Commodore Dynamic Total Vision", "Amiga 500 Plus", "Amiga 600HD",
            "Amiga 1200HD", "Amiga 4000/030", "Amiga 4000/040", "Drean Commodore 64", "Commodore LCD",
            "Commodore 900", "Commodore PC Compatible", "PC-1", "PC-10", "PC-20", "PC-30", "PC-40",
            "PC-60", "Colt", "Commodore 386", "Commodore 486", "Commodore Tower"
        });

        // Computer Models - Atari
        tags.AddRange(new[]
        {
            "Atari 400", "Atari 800", "Atari 600XL", "Atari 800XL", "Atari 1200XL", "Atari 65XE",
            "Atari 130XE", "Atari 800XE", "Atari XEGS", "XE Game System", "Atari 520ST", "Atari 520STf",
            "Atari 520STfm", "Atari 520ST+", "Atari 1040ST", "Atari 1040STf", "Atari 1040STfm",
            "Atari 1040STE", "Atari 2080ST", "Atari 4160ST", "Atari Mega ST", "Mega ST1", "Mega ST2",
            "Mega ST4", "Atari Mega STE", "Atari TT030", "Atari Falcon", "Falcon030", "Atari STacy",
            "Atari ST Book", "Atari Portfolio", "Atari Lynx", "Atari Jaguar", "Atari 2600", "Atari 5200",
            "Atari 7800", "Atari 8-bit", "Atari 16-bit", "Atari 32-bit", "Atari Transputer Workstation",
            "ATW-800", "Atari PC", "PC1", "PC2", "PC3", "PC4", "PC5", "ABC 286", "ABC 386", "Atari N386",
            "Atari 486", "Atari Vortex"
        });

        // Computer Models - IBM and Compatibles
        tags.AddRange(new[]
        {
            "IBM PC", "IBM PC 5150", "IBM PC XT", "IBM PC AT", "IBM PC AT 5170", "IBM PCjr", "IBM PS/1",
            "IBM PS/2", "PS/2 Model 25", "PS/2 Model 30", "PS/2 Model 35", "PS/2 Model 40", "PS/2 Model 50",
            "PS/2 Model 55", "PS/2 Model 60", "PS/2 Model 70", "PS/2 Model 80", "PS/2 Model 90",
            "PS/2 Model 95", "IBM PS/ValuePoint", "IBM PC Convertible", "IBM ThinkPad", "ThinkPad 300",
            "ThinkPad 500", "ThinkPad 700", "ThinkPad 701", "ThinkPad 701C", "ThinkPad Butterfly",
            "IBM Aptiva", "IBM NetVista", "IBM IntelliStation", "IBM RS/6000", "IBM RT PC", "IBM System/23",
            "IBM System/34", "IBM System/36", "IBM System/38", "IBM AS/400", "IBM System i", "IBM System p",
            "IBM System x", "IBM System z", "IBM 5100", "IBM 5110", "IBM 5120", "IBM 5140", "IBM 5155",
            "IBM 5160", "IBM 5162", "IBM 5170", "IBM 3270 PC", "IBM 5271", "IBM 5272", "IBM 5273",
            "IBM Personal System/55", "IBM WorkPad", "IBM PC Server", "IBM EduQuest"
        });

        // Computer Models - Tandy/Radio Shack
        tags.AddRange(new[]
        {
            "TRS-80", "TRS-80 Model I", "TRS-80 Model II", "TRS-80 Model III", "TRS-80 Model 4",
            "TRS-80 Model 4P", "TRS-80 Model 4D", "TRS-80 Model 12", "TRS-80 Model 16", "TRS-80 Model 6000",
            "TRS-80 Color Computer", "CoCo", "CoCo 1", "CoCo 2", "CoCo 3", "TRS-80 MC-10", "TRS-80 Model 100",
            "TRS-80 Model 102", "TRS-80 Model 200", "TRS-80 Model 600", "TRS-80 PC-1", "TRS-80 PC-2",
            "TRS-80 PC-3", "TRS-80 PC-4", "TRS-80 Pocket Computer", "Tandy 1000", "Tandy 1000A", "Tandy 1000HD",
            "Tandy 1000EX", "Tandy 1000HX", "Tandy 1000SX", "Tandy 1000TX", "Tandy 1000SL", "Tandy 1000SL/2",
            "Tandy 1000TL", "Tandy 1000TL/2", "Tandy 1000TL/3", "Tandy 1000RL", "Tandy 1000RL-HD",
            "Tandy 1000RLX", "Tandy 1000RLX-HD", "Tandy 1000RSX", "Tandy 2000", "Tandy 2500", "Tandy 3000",
            "Tandy 4000", "Tandy 5000", "Tandy 6000", "Tandy 1100FD", "Tandy 1200", "Tandy 1400LT",
            "Tandy 1400FD", "Tandy 2800", "Tandy 2810", "Tandy 2820", "Tandy 3800", "Tandy 3810", "Tandy 3820",
            "Tandy 4800", "Tandy 4810", "Tandy 4820", "Tandy 4825", "Tandy 4850", "Tandy Sensation",
            "Tandy VIS", "Tandy Zoomer", "Tandy WP-2", "Tandy Grid"
        });

        // Computer Models - Sinclair
        tags.AddRange(new[]
        {
            "Sinclair ZX80", "Sinclair ZX81", "Timex Sinclair 1000", "TS1000", "Timex Sinclair 1500",
            "TS1500", "Timex Sinclair 2068", "TS2068", "Sinclair ZX Spectrum", "ZX Spectrum 16K",
            "ZX Spectrum 48K", "ZX Spectrum Plus", "ZX Spectrum 128", "ZX Spectrum 128K", "ZX Spectrum +2",
            "ZX Spectrum +2A", "ZX Spectrum +2B", "ZX Spectrum +3", "Pentagon", "Scorpion", "ATM Turbo",
            "Sinclair QL", "Quantum Leap", "Sinclair PC200", "Sinclair PC500", "Cambridge Z88", "A4 Computer",
            "MK14", "Sinclair Scientific", "Sinclair Programmable", "Sinclair Enterprise", "Enterprise 64",
            "Enterprise 128", "Sam Coupé", "MGT Sam Coupé", "ZX Spectrum Next", "Recreated ZX Spectrum",
            "Sinclair Microdrive", "ZX Interface 1", "ZX Interface 2", "ZX Printer"
        });

        // Computer Models - Amstrad
        tags.AddRange(new[]
        {
            "Amstrad CPC", "CPC 464", "CPC 472", "CPC 664", "CPC 6128", "CPC 464 Plus", "CPC 6128 Plus",
            "GX4000", "Amstrad PCW", "PCW 8256", "PCW 8512", "PCW 9256", "PCW 9512", "PCW 9512+",
            "PCW 10", "PCW 16", "Amstrad PC1512", "PC1512", "Amstrad PC1640", "PC1640", "Amstrad PC2086",
            "PC2086", "Amstrad PC2286", "PC2286", "Amstrad PC2386", "PC2386", "Amstrad PC3086", "PC3086",
            "Amstrad PC3286", "PC3286", "Amstrad PC3386", "PC3386", "Amstrad PC4386", "PC4386",
            "Amstrad PC5086", "PC5086", "Amstrad PC5286", "PC5286", "Amstrad PC5386", "PC5386",
            "Amstrad PC6486", "PC6486", "Amstrad PC7000", "PC7000", "Amstrad PC7386", "PC7386",
            "Amstrad PC7486", "PC7486", "Amstrad PC7586", "PC7586", "Amstrad PC8086", "PC8086",
            "Amstrad PC8286", "PC8286", "Amstrad PC8386", "PC8386", "Amstrad PC8486", "PC8486",
            "Amstrad PC9486", "PC9486", "Amstrad PC9512", "Amstrad PC9600", "PC9600", "Amstrad PPC512",
            "PPC512", "Amstrad PPC640", "PPC640", "Amstrad ALT286", "ALT286", "Amstrad ALT386", "ALT386",
            "Amstrad Mega PC", "Mega PC", "Amstrad NC100", "NC100", "Amstrad NC150", "NC150", "Amstrad NC200",
            "NC200", "Amstrad PenPad", "PenPad PDA600", "Amstrad @mailer", "Amstrad e-m@iler", "Amstrad e-m@iler Plus"
        });

        // Computer Models - Other British Computers
        tags.AddRange(new[]
        {
            "BBC Micro", "BBC Model A", "BBC Model B", "BBC Model B+", "BBC Master", "BBC Master 128",
            "BBC Master Compact", "BBC Master 512", "BBC Master Turbo", "BBC Master AIV", "BBC Master ET",
            "Acorn Electron", "Acorn Atom", "Acorn System 1", "Acorn System 2", "Acorn System 3",
            "Acorn System 4", "Acorn System 5", "Acorn Archimedes", "Archimedes 305", "Archimedes 310",
            "Archimedes 410", "Archimedes 420", "Archimedes 440", "Archimedes 540", "Archimedes A3000",
            "Archimedes A3010", "Archimedes A3020", "Archimedes A4000", "Archimedes A5000", "Archimedes A7000",
            "Acorn RiscPC", "RiscPC 600", "RiscPC 700", "StrongARM RiscPC", "Acorn A4", "Acorn A7000+",
            "Acorn Phoebe", "Acorn Network Computer", "Acorn NewsPad", "Iyonix PC", "Dragon 32", "Dragon 64",
            "Dragon 128", "Dragon 200", "Dragon Professional", "Dragon Beta", "Tano Dragon", "Welsh Dragon",
            "Oric-1", "Oric Atmos", "Oric Telestrat", "Oric Stratos", "Oric Nova 64", "Camputers Lynx",
            "Lynx 48", "Lynx 96", "Lynx 128", "Jupiter Ace", "Memotech MTX500", "MTX512", "MTX512S",
            "Memotech RS128", "Tatung Einstein", "Einstein TC-01", "Einstein 256", "Grundy NewBrain",
            "NewBrain AD", "NewBrain A", "NewBrain MD", "Torch Computers", "Torch C Series", "Torch CH Series",
            "Torch XXX", "Torch Graduate", "Torch Unicorn", "Torch Triple X", "Research Machines 380Z",
            "RM Nimbus", "RM Nimbus PC-186", "RM Nimbus PC-286", "RM Nimbus PC-386", "RM Nimbus PC-486",
            "Apricot PC", "Apricot Xi", "Apricot Xen", "Apricot F1", "Apricot F10", "Apricot FT",
            "Apricot LS", "Apricot VX", "Apricot XEN-S", "Apricot XEN-LS", "Apricot XEN-i",
            "ICL One Per Desk", "ICL OPD", "ICL DRS", "Merlin M4000", "Merlin Tonto"
        });

        // Computer Models - Japanese Computers
        tags.AddRange(new[]
        {
            "NEC PC-6001", "NEC PC-6601", "NEC PC-8001", "NEC PC-8801", "NEC PC-8801mkII", "NEC PC-8801mkIISR",
            "NEC PC-8801mkIIFR", "NEC PC-8801mkIIMR", "NEC PC-8801mkIITR", "NEC PC-8801FH", "NEC PC-8801MH",
            "NEC PC-8801FA", "NEC PC-8801MA", "NEC PC-8801FE", "NEC PC-8801MA2", "NEC PC-8801FE2",
            "NEC PC-8801MC", "NEC PC-9801", "NEC PC-9801F", "NEC PC-9801M", "NEC PC-9801U", "NEC PC-9801VF",
            "NEC PC-9801VM", "NEC PC-9801UV", "NEC PC-9801VX", "NEC PC-9801RA", "NEC PC-9801RS", "NEC PC-9801RX",
            "NEC PC-9801DA", "NEC PC-9801DS", "NEC PC-9801DX", "NEC PC-9801FA", "NEC PC-9801FS", "NEC PC-9801FX",
            "NEC PC-9821", "NEC PC-98", "NEC PC-88", "NEC PC-88VA", "NEC PC-100", "NEC APC", "NEC APC III",
            "NEC Trek", "NEC TK-80", "NEC TK-85", "Sharp MZ-80K", "Sharp MZ-80C", "Sharp MZ-80A", "Sharp MZ-80B",
            "Sharp MZ-700", "Sharp MZ-800", "Sharp MZ-1200", "Sharp MZ-1500", "Sharp MZ-2000", "Sharp MZ-2200",
            "Sharp MZ-2500", "Sharp MZ-2800", "Sharp MZ-3500", "Sharp MZ-5500", "Sharp MZ-6500", "Sharp X1",
            "Sharp X1 Turbo", "Sharp X1 Turbo Z", "Sharp X68000", "X68000 ACE", "X68000 EXPERT", "X68000 PRO",
            "X68000 SUPER", "X68000 XVI", "X68000 Compact", "X68030", "Sharp PC-1211", "Sharp PC-1500",
            "Sharp PC-3000", "Sharp PC-5000", "Sharp PC-7000", "Sharp PC-E500", "Sharp Zaurus",
            "Fujitsu FM-7", "FM-77", "FM-77AV", "FM Towns", "FM Towns Marty", "Fujitsu FM-8", "FM-11",
            "FM-16β", "FM-R", "Hitachi Basic Master", "Basic Master Level 1", "Basic Master Level 2",
            "Basic Master Level 3", "Basic Master Jr", "Hitachi S1", "Hitachi MB-H1", "MB-H2", "MB-H50",
            "MB-S1", "Toshiba Pasopia", "Pasopia 7", "Pasopia 16", "Pasopia IQ", "Toshiba J-3100",
            "Sony SMC-70", "SMC-777", "Sony HB-10", "HB-20", "HB-55", "HB-75", "HB-101", "HB-201",
            "HB-501", "HB-701", "HB-F1", "HB-F1II", "HB-F1XD", "HB-F1XDJ", "HB-F1XDMK2", "HB-F5",
            "HB-F9", "HB-F500", "HB-F700", "HB-F900", "HB-G900", "Sony VAIO", "Panasonic FS-A1",
            "FS-A1F", "FS-A1FX", "FS-A1WX", "FS-A1WSX", "FS-A1GT", "FS-A1ST", "Panasonic CF-2700",
            "CF-3000", "CF-3300", "Sanyo PHC-25", "PHC-28", "PHC-30", "PHC-35", "PHC-55", "PHC-64",
            "PHC-70", "PHC-77", "Sanyo MBC-550", "MBC-555", "MBC-775", "Sanyo Wavy", "Wavy 10", "Wavy 11",
            "Wavy 22", "Wavy 23", "Wavy 25", "Wavy 35", "Wavy 55", "Wavy 70", "Wavy 77"
        });

        // MSX Computers
        tags.AddRange(new[]
        {
            "MSX", "MSX1", "MSX2", "MSX2+", "MSX turbo R", "Spectravideo SV-318", "SV-328", "SVI-728",
            "SVI-738", "SVI-838", "Yamaha CX5M", "CX5MII", "CX7M", "CX11", "YIS503", "YIS604", "YIS805",
            "Philips VG-8000", "VG-8010", "VG-8020", "VG-8230", "VG-8235", "VG-8240", "VG-8245", "VG-8247",
            "VG-8248", "NMS-8220", "NMS-8245", "NMS-8250", "NMS-8255", "NMS-8260", "NMS-8270", "NMS-8280",
            "Canon V-8", "V-10", "V-20", "V-25", "V-30", "V-30F", "Canon VF-100", "Casio MX-10", "MX-15",
            "MX-101", "MX-201", "PV-7", "PV-16", "Daewoo CPC-200", "CPC-300", "CPC-330", "CPC-400",
            "CPC-400S", "DPC-100", "DPC-180", "DPC-200", "IQ-1000", "IQ-2000", "Goldstar FC-80",
            "FC-150", "FC-200", "GFC-1080", "Gradiente Expert", "Expert Plus", "Expert DDPlus", "Expert XP-800",
            "Hotbit HB-8000", "National CF-1200", "CF-2000", "CF-2700", "CF-3000", "CF-3300", "FS-4000",
            "FS-4500", "FS-4600", "FS-4700", "FS-5000", "FS-5500"
        });

        // Computer Models - Other American Computers
        tags.AddRange(new[]
        {
            "Compaq Portable", "Compaq Portable Plus", "Compaq Portable II", "Compaq Portable III",
            "Compaq Portable 386", "Compaq Portable 486", "Compaq SLT", "Compaq LTE", "Compaq Deskpro",
            "Compaq Deskpro 286", "Compaq Deskpro 386", "Compaq Deskpro 486", "Compaq Deskpro 586",
            "Compaq Prolinea", "Compaq Presario", "Texas Instruments TI-99/4", "TI-99/4A", "TI-99/2",
            "TI-99/8", "Texas Instruments Professional Computer", "TI Professional", "TI Portable Professional",
            "TI-74", "TI-95", "TI CC-40", "Compact Computer 40", "Texas Instruments Avigo", "DEC Rainbow",
            "Rainbow 100", "Rainbow 100+", "Rainbow 190", "DEC Professional", "Professional 325", "Professional 350",
            "Professional 380", "DECmate", "DECmate I", "DECmate II", "DECmate III", "DEC VAXstation",
            "VAXstation I", "VAXstation II", "VAXstation 2000", "VAXstation 3100", "VAXstation 3200",
            "VAXstation 3500", "VAXstation 3520", "VAXstation 3540", "VAXstation 4000", "DEC VT180",
            "VT185", "Robin", "DEC Multia", "DEC AlphaStation", "DEC AlphaServer", "Sun-1", "Sun-2",
            "Sun-3", "Sun-4", "SPARCstation", "SPARCstation 1", "SPARCstation 2", "SPARCstation 5",
            "SPARCstation 10", "SPARCstation 20", "SPARCserver", "SPARCcenter", "Sun Ultra", "Ultra 1",
            "Ultra 2", "Ultra 5", "Ultra 10", "Ultra 30", "Ultra 60", "Ultra 80", "Sun Blade",
            "Sun JavaStation", "Silicon Graphics IRIS", "IRIS 1000", "IRIS 2000", "IRIS 3000", "IRIS 4D",
            "SGI Indigo", "Indigo Elan", "Indigo XS", "Indigo XZ", "Indigo R3000", "Indigo R4000",
            "SGI Indigo2", "Indigo2 IMPACT", "SGI Indy", "SGI O2", "SGI Octane", "SGI Onyx", "SGI Origin",
            "SGI Challenge", "SGI Crimson", "SGI Personal IRIS", "SGI Power Series", "SGI Professional IRIS",
            "NeXT Computer", "NeXTcube", "NeXTstation", "NeXTstation Color", "NeXTstation Turbo",
            "NeXTstation Turbo Color", "NeXTcube Turbo", "NeXTdimension", "BeBox", "Be Inc BeBox",
            "HP Vectra", "HP 9000", "HP 3000", "HP 2000", "HP-85", "HP-86", "HP-87", "HP-150", "HP Integral PC",
            "HP Pavilion", "Gateway 2000", "Gateway Solo", "Gateway Destination", "Packard Bell Legend",
            "Packard Bell Force", "Packard Bell Platinum", "Packard Bell Navigator", "AST Premium",
            "AST Bravo", "AST Adventure", "AST Advantage", "ALR Evolution", "ALR Revolution", "ALR PowerPro",
            "ALR PowerFlex", "ALR PowerVEISA", "Zenith Z-80", "Z-89", "Z-90", "Z-100", "Z-110", "Z-120",
            "Z-150", "Z-160", "Z-170", "Z-180", "Z-200", "Z-248", "Z-286", "Z-386", "Z-Station",
            "Zenith SupersPort", "Zenith TurbosPort", "Zenith MinisPort", "Zenith MastersPort", "Heath H8",
            "Heath H11", "Heath H19", "Heath H89", "Heathkit H8", "Heathkit H11", "Heathkit H89", "HERO-1",
            "HERO-2000", "HERO Jr", "Eagle Computer", "Eagle 1600", "Eagle II", "Eagle III", "Eagle IV",
            "Eagle PC", "Eagle PC Plus", "Eagle Spirit", "Eagle Turbo", "Franklin ACE", "ACE 100", "ACE 200",
            "ACE 500", "ACE 1000", "ACE 1200", "ACE 2000", "ACE 2100", "ACE 2200", "Franklin PC8000"
        });

        // Computer Models - Other European Computers
        tags.AddRange(new[]
        {
            "Olivetti M10", "M15", "M20", "M21", "M24", "M24SP", "M28", "M200", "M240", "M280", "M290",
            "M300", "M380", "M400", "Olivetti Prodest", "Prodest PC1", "Prodest PC128", "Thomson MO5",
            "MO6", "TO7", "TO7-70", "TO8", "TO8D", "TO9", "TO9+", "Thomson MO5NR", "MO5E", "TO16",
            "Exelvision EXL 100", "Alcyane", "Victor Lambda", "Hector", "Interact", "Alice", "Alice 32",
            "Alice 90", "MC-10", "Schneider CPC", "Schneider Euro PC", "Euro XT", "Euro AT", "Tower PC",
            "Tower AT", "Robotron KC 85", "KC 85/1", "KC 85/2", "KC 85/3", "KC 85/4", "KC 87",
            "Robotron Z1013", "Robotron A5105", "Robotron 1715", "Robotron A7100", "Robotron A7150",
            "Robotron EC 1834", "Robotron CM 1910", "Pravetz 8", "Pravetz 8A", "Pravetz 8C", "Pravetz 8D",
            "Pravetz 8E", "Pravetz 8M", "Pravetz 16", "Pravetz 82", "Pravetz 8S", "IMKO-1", "IMKO-2",
            "Pyldin", "Pyldin-601", "Oric", "Oric-1", "Oric Atmos", "Oric Telestrat", "Oric Stratos",
            "Oric Nova 64", "Squale", "Goupil", "Goupil 1", "Goupil 2", "Goupil 3", "Goupil G4", "Goupil G5",
            "SMT Goupil", "Bull Micral", "Micral N", "Micral S", "Micral 30", "Micral 45", "Micral 60",
            "Micral 80", "Micral 90", "Bull Questar", "Questar M", "Questar 400", "Bull DPX", "Sord M5",
            "Sord M23", "Sord M68", "Sord M100ACE", "Sord M200", "Sord M243", "Sord M343", "Sord IS-11",
            "Pecom 32", "Pecom 64", "Galaksija", "Galaksija Plus", "Orao", "Orao 64", "Orao 102", "Orao 103",
            "Partner", "TIM-011", "TIM-100", "TIM-600", "Lola 8", "Lola 8A", "Tesla PMD 85", "PMD 85-1",
            "PMD 85-2", "PMD 85-3", "Tesla Ondra", "Ondra SPO 186", "Ondra ViLi", "IQ 151", "TNS SC",
            "TNS HC", "TNS MC", "TNS GC", "Didaktik", "Didaktik Alfa", "Didaktik Beta", "Didaktik Gama",
            "Didaktik M", "Didaktik Kompakt", "ZX-80 URAL", "Hobbit", "Ocean", "Bashkiria", "Krista",
            "Elektronika BK", "BK-0010", "BK-0011", "BK-0011M", "DVK", "DVK-1", "DVK-2", "DVK-3",
            "Agat", "Agat-4", "Agat-7", "Agat-9", "Korvet", "Mikrosha", "Radio-86RK", "Specialist",
            "UT-88", "Vector-06C", "Iskra", "Iskra 226", "Iskra 1030", "Iskra 1031", "Iskra 1080",
            "Niva", "Poisk", "Poisk-1", "Poisk-2", "ES PEVM", "EC-1840", "EC-1841", "EC-1845", "EC-1849"
        });

        // Operating Systems
        tags.AddRange(new[]
        {
            "MS-DOS", "PC-DOS", "DR-DOS", "Novell DOS", "FreeDOS", "OpenDOS", "CP/M", "CP/M-80", "CP/M-86",
            "CP/M Plus", "CP/M-68K", "MP/M", "MP/M-86", "MP/M II", "Concurrent CP/M", "Concurrent DOS",
            "TRSDOS", "LDOS", "NEWDOS", "DOSPLUS", "MultiDOS", "ProDOS", "Apple DOS", "Apple DOS 3.2",
            "Apple DOS 3.3", "SOS", "GS/OS", "Apple System", "System 1", "System 2", "System 3", "System 4",
            "System 5", "System 6", "System 7", "System 7.5", "Mac OS 7.6", "Mac OS 8", "Mac OS 9",
            "Mac OS Classic", "AmigaOS", "AmigaOS 1.0", "AmigaOS 1.1", "AmigaOS 1.2", "AmigaOS 1.3",
            "AmigaOS 2.0", "AmigaOS 2.1", "AmigaOS 3.0", "AmigaOS 3.1", "AmigaOS 3.5", "AmigaOS 3.9",
            "AmigaOS 4", "Workbench", "Kickstart", "AROS", "MorphOS", "Atari TOS", "TOS", "MultiTOS",
            "MiNT", "MagiC", "Geneva", "GEOS", "GEOS 64", "GEOS 128", "GEOS Apple", "GeoWorks", "PC/GEOS",
            "NewDeal Office", "Breadbox Ensemble", "Windows 1.0", "Windows 2.0", "Windows 2.1", "Windows 3.0",
            "Windows 3.1", "Windows 3.11", "Windows for Workgroups", "Windows 95", "Windows 98", "Windows 98SE",
            "Windows ME", "Windows NT", "Windows NT 3.1", "Windows NT 3.5", "Windows NT 3.51", "Windows NT 4.0",
            "OS/2", "OS/2 1.0", "OS/2 1.1", "OS/2 1.2", "OS/2 1.3", "OS/2 2.0", "OS/2 2.1", "OS/2 Warp",
            "OS/2 Warp 3", "OS/2 Warp 4", "eComStation", "ArcaOS", "BeOS", "BeOS R3", "BeOS R4", "BeOS R5",
            "BeIA", "Haiku", "RISC OS", "RISC OS 2", "RISC OS 3", "RISC OS 4", "RISC OS 5", "RISC OS 6",
            "Arthur", "NeXTSTEP", "OPENSTEP", "Rhapsody", "UNIX", "Xenix", "SCO UNIX", "UnixWare", "AIX",
            "A/UX", "Solaris", "SunOS", "IRIX", "HP-UX", "Ultrix", "OSF/1", "Digital UNIX", "Tru64 UNIX",
            "BSD", "386BSD", "FreeBSD", "NetBSD", "OpenBSD", "Linux", "Minix", "Coherent", "QNX", "QDOS",
            "86-DOS", "MSX-DOS", "MSX-DOS 2", "FlexOS", "GEM", "Atari GEM", "GEM Desktop", "ViewMAX",
            "FreeGEM", "OpenGEM", "Commodore KERNAL", "BASIC ROM", "CBM BASIC", "Commodore DOS", "GEOS 64",
            "JiffyDOS", "TurboDisk", "Sinclair BASIC", "128K BASIC", "+3DOS", "Beta BASIC", "SAM BASIC",
            "MasterDOS", "UniDOS", "SAMDOS", "B-DOS", "GDOS", "G+DOS", "ResiDOS", "OpenSE", "SE Basic",
            "Locomotive BASIC", "AMSDOS", "ParaDOS", "VDOS", "SymbOS", "FutureOS", "Contiki", "LUnix",
            "Wings", "GEOS", "The Final Cartridge", "Action Replay", "Expert Cartridge", "Super Snapshot",
            "Turbo ROM", "Dolphin DOS", "Speed DOS", "Professional DOS", "Burst ROM", "WarpSpeed"
        });

        // Processors and CPUs
        tags.AddRange(new[]
        {
            "CPU", "Intel 4004", "Intel 4040", "Intel 8008", "Intel 8080", "Intel 8085", "Intel 8086", "Intel 8088",
            "Intel 80186", "Intel 80188", "Intel 80286", "Intel 80386", "Intel 386", "386SX", "386DX",
            "Intel 80486", "Intel 486", "486SX", "486DX", "486DX2", "486DX4", "Intel Pentium", "Pentium 60",
            "Pentium 66", "Pentium 75", "Pentium 90", "Pentium 100", "Pentium 120", "Pentium 133",
            "Pentium 150", "Pentium 166", "Pentium 200", "Pentium MMX", "Pentium Pro", "Pentium II",
            "Pentium III", "Pentium 4", "Intel Celeron", "Intel Xeon", "Intel Core", "Intel Core 2",
            "Intel Core i3", "Intel Core i5", "Intel Core i7", "Intel Core i9", "Intel Atom", "Intel Itanium",
            "Intel i860", "Intel i960", "MOS 6502", "6502", "6502A", "6502B", "6502C", "65C02", "65816",
            "65C816", "MOS 6507", "MOS 6509", "MOS 6510", "MOS 8500", "MOS 8502", "CSG 65CE02", "Hudson HuC6280",
            "WDC 65C02", "WDC 65C816", "Rockwell 6502", "Motorola 6800", "Motorola 6809", "Motorola 68000",
            "68000", "68008", "68010", "68012", "Motorola 68020", "68020", "68EC020", "Motorola 68030",
            "68030", "68EC030", "Motorola 68040", "68040", "68EC040", "68LC040", "Motorola 68060", "68060",
            "68EC060", "68LC060", "Motorola 88000", "88100", "88110", "PowerPC", "PowerPC 601", "PowerPC 603",
            "PowerPC 604", "PowerPC G3", "PowerPC G4", "PowerPC G5", "MPC5200", "Zilog Z80", "Z80", "Z80A",
            "Z80B", "Z80H", "Z8000", "Z8001", "Z8002", "eZ80", "Zilog Z180", "Zilog Z280", "Zilog Z380",
            "Zilog Z800", "NSC800", "R800", "ASCII R800", "AMD Am9080", "AMD 8080A", "AMD Am2900", "AMD Am29000",
            "AMD Am386", "AMD Am486", "AMD 5x86", "AMD K5", "AMD K6", "AMD K6-2", "AMD K6-III", "AMD Athlon",
            "AMD Duron", "AMD Sempron", "AMD Opteron", "AMD Phenom", "AMD FX", "AMD Ryzen", "AMD EPYC",
            "Cyrix 6x86", "Cyrix 5x86", "Cyrix MII", "Cyrix MediaGX", "Cyrix III", "NEC V20", "NEC V30",
            "NEC V40", "NEC V50", "NEC VR4300", "NEC VR5000", "ARM1", "ARM2", "ARM3", "ARM250", "ARM6",
            "ARM7", "ARM7TDMI", "ARM9", "ARM11", "StrongARM", "XScale", "ARM Cortex", "Apple Silicon",
            "Apple M1", "Apple M2", "Texas Instruments TMS9900", "TMS9995", "TMS9918", "TMS9928", "TMS9929",
            "TMS34010", "TMS34020", "National Semiconductor NS32016", "NS32032", "NS32532", "SC/MP",
            "PACE", "INS8060", "INS8070", "INS8073", "Western Design Center W65C02", "W65C816", "W65C134",
            "W65C265", "Fairchild F8", "RCA 1802", "COSMAC", "CDP1802", "Intersil 6100", "Harris 6100",
            "DEC Alpha", "Alpha 21064", "Alpha 21164", "Alpha 21264", "Alpha 21364", "Alpha 21464",
            "MIPS R2000", "R3000", "R4000", "R4400", "R5000", "R6000", "R8000", "R10000", "R12000",
            "R14000", "R16000", "SPARC", "SuperSPARC", "HyperSPARC", "UltraSPARC", "UltraSPARC II",
            "UltraSPARC III", "UltraSPARC IV", "UltraSPARC T1", "UltraSPARC T2", "Fujitsu SPARC64",
            "PA-RISC", "PA-7000", "PA-7100", "PA-7200", "PA-7300", "PA-8000", "PA-8200", "PA-8500",
            "PA-8600", "PA-8700", "PA-8800", "PA-8900", "Hitachi 6309", "Hitachi SH-1", "SH-2", "SH-3",
            "SH-4", "SuperH", "Renesas RX", "Renesas RL78", "Renesas V850", "Transmeta Crusoe", "Transmeta Efficeon",
            "VIA C3", "VIA C7", "VIA Nano", "IDT WinChip", "Rise mP6", "Geode", "MediaGX", "Geode GX",
            "Geode LX", "Geode NX", "Am5x86", "Élan SC300", "Élan SC400", "Élan SC520"
        });

        // Graphics and Sound Chips
        tags.AddRange(new[]
        {
            "MOS VIC", "VIC-I", "VIC-II", "VIC-20 VIC", "C64 VIC-II", "MOS VIC-IIe", "MOS VDC", "8563 VDC",
            "8568 VDC", "MOS SID", "SID 6581", "SID 6582", "SID 8580", "MOS TED", "7360 TED", "8360 TED",
            "CSG 4567", "SuperCPU", "Agnus", "OCS Agnus", "ECS Agnus", "Fat Agnus", "Super Agnus", "Alice",
            "AGA Alice", "Denise", "OCS Denise", "ECS Denise", "Super Denise", "Lisa", "AGA Lisa", "Paula",
            "Gary", "Gayle", "Budgie", "Buster", "Super Buster", "Bridgette", "Ramsey", "DMAC", "Amber",
            "Akiko", "ANTIC", "GTIA", "CTIA", "FREDDIE", "POKEY", "GUMBY", "CGIA", "FGTIA", "VBXE",
            "Yamaha V9938", "V9958", "V9990", "V9978", "YM2149", "YM2151", "YM2203", "YM2413", "YM2608",
            "YM2610", "YM2612", "YM3526", "YM3812", "YMF262", "YMF278", "YMF7", "AY-3-8910", "AY-3-8912",
            "AY-3-8913", "General Instrument AY-3-8910", "TI SN76489", "SN76494", "SN76496", "TI TMS9918",
            "TMS9928", "TMS9929", "TMS9118", "TMS9128", "TMS9129", "TMS5220", "TMS9918A", "TMS9928A",
            "TMS9929A", "Motorola 6845", "6845 CRTC", "HD6845", "MC6845", "SY6545", "SY6845", "R6545",
            "Motorola 6847", "MC6847", "Intel 8275", "8275 CRT", "NEC μPD7220", "GDC", "Graphics Display Controller",
            "Chips and Technologies", "C&T", "82C451", "82C452", "82C453", "F82C451", "F82C452", "F82C453",
            "Tseng Labs ET3000", "ET4000", "ET4000AX", "ET4000/W32", "ET6000", "ET6100", "Trident TVGA8800",
            "TVGA8900", "TVGA9000", "TGUI9440", "TGUI9680", "TGUI9682", "TGUI9685", "Blade3D", "CyberBlade",
            "Paradise PVGA1", "WD90C00", "WD90C10", "WD90C11", "WD90C20", "WD90C24", "WD90C26", "WD90C30",
            "WD90C31", "WD90C33", "ATI Wonder", "EGA Wonder", "VGA Wonder", "Graphics Solution", "8514/Ultra",
            "Mach8", "Mach32", "Mach64", "Rage", "Rage II", "Rage IIC", "Rage Pro", "Rage 128", "Rage Fury",
            "Radeon", "S3 Graphics", "S3 911", "S3 924", "S3 801", "S3 805", "S3 928", "S3 864", "S3 964",
            "S3 Trio", "S3 Trio32", "S3 Trio64", "S3 ViRGE", "S3 Savage", "Savage3D", "Savage4", "Savage 2000",
            "Matrox MGA", "Millennium", "Mystique", "G100", "G200", "G400", "G450", "G550", "Parhelia",
            "Cirrus Logic", "CL-GD5420", "CL-GD5422", "CL-GD5424", "CL-GD5426", "CL-GD5428", "CL-GD5429",
            "CL-GD5430", "CL-GD5434", "CL-GD5436", "CL-GD5440", "CL-GD5446", "CL-GD5462", "CL-GD5464",
            "CL-GD5465", "CL-GD5480", "Laguna", "Laguna3D", "Oak Technology", "OTI037", "OTI057", "OTI067",
            "OTI077", "OTI087", "Warp 5", "Video7", "V7 VGA", "VEGA", "VEGA VGA", "FastWrite", "VRAMll",
            "1024i", "Genoa", "SuperVGA", "SuperEGA", "WindowsVGA", "Orchid", "ProDesigner", "ProDesigner II",
            "Fahrenheit", "Righteous 3D", "Number Nine", "Revolution", "Imagine", "Hercules Graphics Card",
            "Hercules Color Card", "Hercules InColor", "Graphics Card Plus", "Hercules VGA", "Dynamite",
            "Stingray", "Terminator", "Thriller", "Graphite", "CGA", "Color Graphics Adapter", "EGA",
            "Enhanced Graphics Adapter", "VGA", "Video Graphics Array", "SVGA", "Super VGA", "XGA",
            "Extended Graphics Array", "8514/A", "TIGA", "MCGA", "Multi-Color Graphics Array", "MDA",
            "Monochrome Display Adapter", "HGC", "PGC", "Professional Graphics Controller", "PCjr Video",
            "Tandy Graphics Adapter", "TGA", "Plantronics Colorplus", "ATI Small Wonder", "Tecmar Graphics Master",
            "Quadram QuadEGA+", "STB Graphics Plus", "Vega Deluxe", "Sigma Designs Color 400", "Artist 1",
            "Artist 1 Plus", "Artist 2", "Artist 10", "Artist 12", "Artist XJ10", "Verticom MX", "MX2",
            "Everex Graphics Edge", "Micro Enhancer", "Vision VGA", "ViewPoint", "Boca Super VGA",
            "Boca SuperX", "Boca Voyager", "Boca Vortex", "Genoa SuperSpectrum", "6400", "6600", "7900",
            "Orchid Technology", "Rampage", "Conquest", "Liberation", "SoundBlaster", "AdLib", "AdLib Gold",
            "Roland MT-32", "MT-100", "CM-32L", "CM-64", "LAPC-I", "MPU-401", "Sound Canvas", "SC-55",
            "SC-88", "Gravis Ultrasound", "GUS", "GUS MAX", "GUS ACE", "GUS PnP", "Pro Audio Spectrum",
            "PAS", "PAS Plus", "PAS 16", "Audio Excel", "Thunder Board", "Sound Galaxy", "Aria", "Mozart",
            "Forte", "ESS AudioDrive", "ES688", "ES1688", "ES1868", "ES1869", "ES1887", "ES1888", "Aztech",
            "Sound Galaxy", "Washington", "Waverider", "Nova 16", "Crystal", "CS4231", "CS4232", "CS4236",
            "CS4237", "CS4280", "CS4281", "Ensoniq", "Soundscape", "AudioPCI", "Vortex", "Vortex 2",
            "Turtle Beach", "Maui", "Tropez", "Tropez Plus", "Tahiti", "Monterey", "Fiji", "Pinnacle",
            "Multisound", "Classic", "Monterey", "Tahiti", "Pinnacle", "OPTi", "MAD16", "82C924", "82C925",
            "82C928", "82C929", "82C930", "82C931", "Windows Sound System", "WSS", "Covox", "Speech Thing",
            "Sound Master", "Disney Sound Source", "Tandy DAC", "3-voice sound", "PC Speaker", "Beeper",
            "LPT DAC", "Parallel Port DAC", "Stereo-on-1", "StereoFX", "DSS", "Echo", "Echo II", "MIDI",
            "General MIDI", "GM", "GS", "XG", "MPU-401", "Roland MPU", "UART mode", "Intelligent mode",
            "MFC", "Music Feature Card", "IMFC", "IBM Music Feature Card", "Wave Blaster", "DB50XG",
            "SW60XG", "NEC Sound Orchestra", "V", "L", "LS", "NEC 73D", "NEC 86", "PC-9801-26", "PC-9801-73",
            "PC-9801-86", "PC-9801-118", "Speak&Spell", "SSI-263", "Votrax", "SC-01", "SC-02", "Type 'N Talk",
            "SAM", "Software Automatic Mouth", "Smoothtalker", "Mockingboard", "ALF Music Card", "Applied Engineering",
            "Phasor", "ReactiveMicro"
        });

        // Storage and Media
        tags.AddRange(new[]
        {
            "Floppy Disk", "Floppy", "Diskette", "3.5 inch", "3.5\"", "5.25 inch", "5.25\"", "8 inch", "8\"",
            "360KB", "720KB", "1.2MB", "1.44MB", "2.88MB", "Single Sided", "Double Sided", "Single Density",
            "Double Density", "High Density", "Extra Density", "Hard Disk", "Hard Drive", "HDD", "MFM",
            "RLL", "IDE", "ATA", "PATA", "SATA", "SCSI", "SCSI-1", "SCSI-2", "SCSI-3", "Ultra SCSI",
            "Wide SCSI", "Fast SCSI", "Ultra Wide SCSI", "SAS", "ESDI", "ST-506", "ST-412", "SMD",
            "Seagate", "Western Digital", "Quantum", "Maxtor", "Conner", "Micropolis", "Fujitsu", "IBM",
            "Hitachi", "Toshiba", "Samsung", "NEC", "CDC", "DEC", "Rodime", "Tandon", "Miniscribe", "Kalok",
            "Priam", "Vertex", "Tulin", "JTS", "Areal", "Integral", "PrairieTek", "JVC", "Syquest", "SyQuest",
            "EZ Drive", "EZ Flyer", "SparQ", "SyJet", "Quest", "Zip Drive", "Zip Disk", "Zip 100", "Zip 250",
            "Zip 750", "Jaz Drive", "Jaz 1GB", "Jaz 2GB", "Bernoulli Box", "Bernoulli Disk", "LS-120",
            "SuperDisk", "LS-240", "Floptical", "UHD144", "HiFD", "Caleb UHD144", "Sony HiFD", "Ditto",
            "Ditto Max", "Travan", "TR-1", "TR-2", "TR-3", "TR-4", "TR-5", "QIC", "QIC-40", "QIC-80",
            "QIC-120", "QIC-150", "QIC-525", "QIC-1000", "QIC-2000", "QIC-3000", "DC300", "DC600", "DC6000",
            "DC2000", "DC2120", "Tape Drive", "Tape Backup", "DAT", "DDS", "DDS-1", "DDS-2", "DDS-3", "DDS-4",
            "DAT72", "DAT160", "DAT320", "8mm Tape", "Exabyte", "AIT", "AIT-1", "AIT-2", "AIT-3", "AIT-4",
            "AIT-5", "Mammoth", "M1", "M2", "LTO", "Ultrium", "LTO-1", "LTO-2", "LTO-3", "LTO-4", "LTO-5",
            "DLT", "DLT2000", "DLT4000", "DLT7000", "DLT8000", "SDLT", "SDLT220", "SDLT320", "SDLT600",
            "VS80", "VS160", "VXA", "VXA-1", "VXA-2", "VXA-3", "CD-ROM", "CD-R", "CD-RW", "DVD-ROM", "DVD-R",
            "DVD-RW", "DVD+R", "DVD+RW", "DVD-RAM", "HD-DVD", "Blu-ray", "BD-R", "BD-RE", "BD-ROM",
            "MiniDisc", "MD", "Hi-MD", "MO", "Magneto-Optical", "3.5\" MO", "5.25\" MO", "128MB MO", "230MB MO",
            "540MB MO", "640MB MO", "1.3GB MO", "2.3GB MO", "Phase Change", "PD", "PD Drive", "DVD-RAM",
            "UDO", "Ultra Density Optical", "WORM", "Write Once", "Laserdisc", "LD", "CED", "SelectaVision",
            "VHD", "Video High Density", "CD Video", "CDV", "Video CD", "VCD", "SVCD", "Photo CD",
            "Compact Cassette", "Cassette Tape", "Audio Cassette", "Kansas City Standard", "Tarbell",
            "CUTS", "CompuTape", "Datasette", "C2N", "1530", "1531", "Microdrive", "ZX Microdrive",
            "Sinclair Microdrive", "Rotronics Wafadrive", "Stringy Floppy", "Exatron", "3\" Disk", "CF2",
            "Amstrad 3\"", "Tatung 3\"", "Quick Disk", "QD", "Mitsumi Quick Disk", "Famicom Disk", "FDS",
            "Amdek AMDC", "Video Floppy", "Mavipak", "VF", "SmartMedia", "SM", "CompactFlash", "CF",
            "CF Type I", "CF Type II", "Microdrive", "IBM Microdrive", "Memory Stick", "Memory Stick Pro",
            "Memory Stick Duo", "SD Card", "SDHC", "SDXC", "miniSD", "microSD", "MMC", "MultiMediaCard",
            "RS-MMC", "xD", "xD-Picture Card", "PCMCIA", "PC Card", "CardBus", "ExpressCard", "Flash Memory",
            "Flash ROM", "EEPROM", "EPROM", "PROM", "ROM Cartridge", "Cartridge", "Cart", "Game Pak",
            "HuCard", "PC Engine Card", "TurboChip", "Bee Card", "SuFami Turbo", "Satellaview", "64DD",
            "N64 Disk Drive", "Famicom Disk System", "FDS", "e-Reader", "Card e-Reader", "DataPlay",
            "Matrix ROM", "ROM Pack", "Solid State Cartridge", "Tape", "Paper Tape", "Punch Card", "Punch Tape",
            "Magnetic Stripe", "Magnetic Card", "Drum Memory", "Magnetic Drum", "Core Memory", "Magnetic Core",
            "Delay Line Memory", "Mercury Delay Line", "Williams Tube", "Selectron Tube", "Bubble Memory",
            "Twistor Memory", "Plated Wire Memory", "Thin Film Memory", "CRAM", "Card Random Access Memory",
            "Data Cell", "Race Track Memory", "Holographic Memory", "Millipede Memory", "3D XPoint", "Optane",
            "MRAM", "FeRAM", "PRAM", "Phase-change", "RRAM", "ReRAM", "Memristor", "NRAM", "Carbon Nanotube",
            "FeFET"
        });

        // Peripherals and Accessories
        tags.AddRange(new[]
        {
            "Keyboard", "Mechanical Keyboard", "Membrane Keyboard", "Rubber Dome", "Buckling Spring",
            "Foam and Foil Keyboard", "Cherry MX", "Alps Switch", "Topre", "Model M", "Model F", "Space Cadet",
            "Happy Hacking", "Apple Keyboard", "Apple Desktop Bus", "ADB Keyboard", "Extended Keyboard", "Extended Keyboard II",
            "Adjustable Keyboard", "Apple Keyboard II", "AppleDesign Keyboard", "USB Keyboard", "Wireless Keyboard",
            "Bluetooth Keyboard", "Mouse", "Ball Mouse", "Mechanical Mouse", "Optical Mouse", "Laser Mouse",
            "Wireless Mouse", "Serial Mouse", "PS/2 Mouse", "Bus Mouse", "ADB Mouse", "USB Mouse",
            "Apple Mouse", "Macintosh Mouse", "Apple Desktop Bus Mouse", "Hockey Puck Mouse", "Mighty Mouse",
            "Magic Mouse", "Microsoft Mouse", "IntelliMouse", "IBM Mouse", "Logitech Mouse", "Genius Mouse",
            "Trackball", "Kensington Trackball", "Logitech Trackball", "Microsoft Trackball", "Trackpad",
            "Touchpad", "Graphics Tablet", "Digitizer", "Wacom Tablet", "CalComp", "Summagraphics", "Kurta",
            "Light Pen", "Light Gun", "NES Zapper", "Sega Light Phaser", "Justifier", "Super Scope",
            "GunCon", "Menacer", "Stunner", "Joystick", "Atari Joystick", "Competition Pro", "QuickShot",
            "QuickJoy", "TAC-2", "Wico", "Kraft", "CH Products", "Flightstick", "Thrustmaster", "Saitek",
            "Gravis", "Gravis Analog", "Gravis GamePad", "Microsoft SideWinder", "Logitech WingMan",
            "Game Controller", "Gamepad", "Joypad", "Control Pad", "D-Pad", "Analog Stick", "Paddle Controller",
            "Paddle", "Driving Controller", "Steering Wheel", "Racing Wheel", "Flight Yoke", "Throttle",
            "Rudder Pedals", "HOTAS", "Power Glove", "U-Force", "Sega Activator", "Dance Pad", "Dance Mat",
            "Guitar Controller", "Drum Controller", "Microphone", "Headset", "Eye Toy", "Kinect", "PlayStation Eye",
            "PlayStation Camera", "Webcam", "QuickCam", "Connectix", "Monitor", "CRT Monitor", "Monochrome Monitor",
            "Green Screen", "Amber Monitor", "Composite Monitor", "RGB Monitor", "VGA Monitor", "SVGA Monitor",
            "Multisync Monitor", "Fixed Frequency", "TTL Monitor", "Analog Monitor", "LCD Monitor", "LCD Panel",
            "Plasma Display", "EGA Monitor", "CGA Monitor", "MDA Monitor", "Hercules Monitor", "TV", "Television",
            "RF Modulator", "TV Tuner", "Video Capture", "Genlock", "Scan Converter", "Scan Doubler",
            "Flicker Fixer", "Line Doubler", "Video Toaster", "NewTek", "Printer", "Dot Matrix", "Dot Matrix Printer",
            "9-pin", "24-pin", "Daisy Wheel", "Daisy Wheel Printer", "Thermal Printer", "Thermal Transfer",
            "Inkjet", "Inkjet Printer", "Bubble Jet", "DeskJet", "StyleWriter", "LaserJet", "Laser Printer",
            "LaserWriter", "PostScript", "PCL", "Epson FX", "FX-80", "FX-85", "FX-100", "LQ-500", "LQ-850",
            "LQ-1050", "LX-80", "LX-800", "LX-810", "MX-80", "MX-100", "RX-80", "Star Micronics", "Star NL-10",
            "Star LC-10", "Star LC-24", "Star NX", "Okidata", "OKI", "Microline", "Okimate", "Panasonic KX-P",
            "Citizen", "Brother", "Canon BJ", "BubbleJet", "HP DeskJet", "HP LaserJet", "Apple ImageWriter",
            "ImageWriter II", "ImageWriter LQ", "Apple LaserWriter", "LaserWriter Plus", "LaserWriter II",
            "StyleWriter", "Personal LaserWriter", "Color StyleWriter", "Plotter", "Pen Plotter", "HP Plotter",
            "Roland Plotter", "CalComp Plotter", "Houston Instrument", "Scanner", "Flatbed Scanner", "Hand Scanner",
            "Handy Scanner", "Sheet Fed Scanner", "Drum Scanner", "Film Scanner", "Slide Scanner", "SCSI Scanner",
            "Parallel Scanner", "USB Scanner", "TWAIN", "SANE", "OCR", "Optical Character Recognition",
            "Modem", "300 Baud", "1200 Baud", "2400 Baud", "9600 Baud", "14.4K", "28.8K", "33.6K", "56K",
            "V.90", "V.92", "V.32", "V.32bis", "V.34", "V.42", "V.42bis", "Bell 103", "Bell 212A", "Hayes",
            "Hayes Compatible", "AT Commands", "Smartmodem", "Sportster", "Courier", "USRobotics", "US Robotics",
            "3Com", "Zoom", "Motorola", "Rockwell", "Lucent", "Conexant", "PC Card Modem", "PCMCIA Modem",
            "External Modem", "Internal Modem", "Acoustic Coupler", "Terminal", "Terminal Emulator", "VT52",
            "VT100", "VT220", "VT320", "VT420", "ANSI Terminal", "Wyse", "Wyse 50", "Wyse 60", "Wyse 85",
            "ADM-3A", "Lear Siegler", "TeleVideo", "Televideo 925", "Heath H19", "Hazeltine", "Hazeltine 1500",
            "IBM 3270", "IBM 5250", "Network Card", "Network Adapter", "NIC", "Ethernet", "10BASE-T", "10BASE-2",
            "10BASE-5", "100BASE-T", "Token Ring", "ARCNET", "LocalTalk", "PhoneNET", "EtherTalk", "AppleTalk",
            "NE1000", "NE2000", "3Com 3C501", "3C503", "3C505", "3C509", "3C905", "Intel EtherExpress",
            "PRO/100", "PRO/1000", "Realtek", "RTL8139", "RTL8169", "Broadcom", "Marvell", "Atheros",
            "Sound Card", "Sound Blaster", "Sound Blaster Pro", "Sound Blaster 16", "Sound Blaster AWE32",
            "Sound Blaster AWE64", "Sound Blaster Live!", "Sound Blaster Audigy", "Sound Blaster X-Fi",
            "AdLib", "AdLib Gold", "Gravis UltraSound", "GUS", "GUS MAX", "Pro Audio Spectrum", "Roland MT-32",
            "Roland LAPC-I", "Roland MPU-401", "Roland SCC-1", "Roland SC-55", "Roland SC-88", "Media Vision",
            "Thunder Board", "Jazz 16", "Orchid SoundWave", "Ensoniq Soundscape", "ESS AudioDrive", "Aztech",
            "OPTi", "Crystal", "Turtle Beach", "Aureal Vortex", "Video Card", "Graphics Card", "VGA Card",
            "SVGA Card", "Graphics Adapter", "Display Adapter", "Graphics Accelerator", "3D Accelerator",
            "3dfx Voodoo", "Voodoo Graphics", "Voodoo2", "Voodoo3", "Voodoo4", "Voodoo5", "Voodoo Rush",
            "Voodoo Banshee", "NVIDIA RIVA", "RIVA 128", "RIVA TNT", "TNT2", "GeForce", "GeForce2", "GeForce3",
            "GeForce4", "ATI Rage", "Rage 128", "Rage Fury", "Radeon", "Radeon 7000", "Radeon 8500", "Radeon 9000",
            "S3 ViRGE", "S3 Savage", "Savage3D", "Savage4", "Savage 2000", "Matrox Millennium", "Matrox Mystique",
            "Matrox G200", "Matrox G400", "Matrox G450", "Cirrus Logic", "Tseng Labs", "Trident", "Paradise",
            "Video Seven", "Chips and Technologies", "Oak Technology", "Realtek", "SiS", "Number Nine",
            "Hercules", "STB", "Diamond", "Orchid", "Genoa", "ATI Wonder", "EGA Wonder", "VGA Wonder",
            "Paradise VGA", "TIGA", "8514/A", "XGA", "Memory Expansion", "RAM Expansion", "Fast RAM", "Chip RAM",
            "Slow RAM", "Zorro", "Zorro II", "Zorro III", "AutoConfig", "A501", "A590", "A2091", "GVP",
            "Great Valley Products", "Supra", "SupraRAM", "AdRAM", "AdSpeed", "ICD", "ICD AdSCSI", "Xetec",
            "FastTrak", "SCSI Controller", "IDE Controller", "Floppy Controller", "FDC", "Multi I/O", "I/O Card",
            "Serial Card", "Parallel Card", "Serial Port", "Parallel Port", "Game Port", "MIDI Interface",
            "RS-232", "RS-422", "RS-485", "Centronics", "IEEE-488", "GPIB", "HPIB", "IEEE-1284", "USB",
            "USB 1.0", "USB 1.1", "USB 2.0", "FireWire", "IEEE 1394", "i.LINK", "Thunderbolt", "Lightning",
            "eSATA", "ExpressCard", "CardBus", "PCMCIA", "PC Card", "ISA", "ISA Bus", "8-bit ISA", "16-bit ISA",
            "EISA", "MCA", "Micro Channel", "VLB", "VESA Local Bus", "VL-Bus", "PCI", "PCI Bus", "AGP",
            "AGP 1x", "AGP 2x", "AGP 4x", "AGP 8x", "PCI-X", "PCI Express", "PCIe", "NuBus", "PDS",
            "Processor Direct Slot", "LC PDS", "S-100", "S-100 Bus", "Altair Bus", "STEbus", "VMEbus",
            "Multibus", "Q-Bus", "Unibus", "MCA", "EISA", "CardBus", "Mini PCI", "Mini PCIe", "M.2",
            "Expansion Chassis", "Docking Station", "Port Replicator", "Breakout Box", "Gender Changer",
            "Null Modem", "Lap Link", "LapLink Cable", "File Transfer Cable", "KVM Switch", "Video Switch",
            "Switch Box", "A/B Switch", "Multiplexer", "Print Buffer", "Print Spooler", "UPS", "Uninterruptible Power Supply",
            "Surge Protector", "Power Strip", "Voltage Regulator", "Power Supply", "PSU", "AT Power Supply",
            "ATX Power Supply", "SFX Power Supply", "Redundant Power Supply", "Modular Power Supply",
            "External Power Supply", "Power Brick", "AC Adapter", "DC Adapter", "Battery Pack", "Rechargeable Battery",
            "NiCd", "NiMH", "Li-Ion", "Lead Acid", "Memory Battery", "CMOS Battery", "Clock Battery",
            "Cooling Fan", "Case Fan", "CPU Fan", "Heatsink", "Heat Spreader", "Thermal Paste", "Thermal Pad",
            "Water Cooling", "Liquid Cooling", "Peltier", "TEC", "Phase Change", "LN2", "Dry Ice"
        });

        // Software and Programming
        tags.AddRange(new[]
        {
            "BASIC", "Microsoft BASIC", "BASICA", "GW-BASIC", "QuickBASIC", "QBasic", "Visual Basic",
            "Commodore BASIC", "Applesoft BASIC", "Integer BASIC", "Atari BASIC", "Sinclair BASIC",
            "BBC BASIC", "AmigaBASIC", "AMOS", "Blitz Basic", "STOS", "GFA BASIC", "Turbo BASIC", "PowerBASIC",
            "Liberty BASIC", "FreeBasic", "Pascal", "Turbo Pascal", "Object Pascal", "Delphi", "Free Pascal",
            "UCSD Pascal", "Apple Pascal", "C", "C++", "Turbo C", "Turbo C++", "Borland C++", "Microsoft C",
            "Lattice C", "Aztec C", "Small C", "Mix C", "Power C", "Watcom C", "DJGPP", "GCC", "Assembly",
            "Assembler", "Machine Language", "Machine Code", "6502 Assembly", "Z80 Assembly", "8086 Assembly",
            "68000 Assembly", "ARM Assembly", "MASM", "TASM", "NASM", "A86", "Debug", "Monitor", "Forth",
            "FIG-Forth", "PolyForth", "SwiftForth", "Win32Forth", "Gforth", "COBOL", "FORTRAN", "Fortran 77",
            "Fortran 90", "PL/I", "Ada", "Modula-2", "Oberon", "Prolog", "LISP", "Common Lisp", "Scheme",
            "Logo", "Smalltalk", "Objective-C", "Java", "JavaScript", "Perl", "Python", "Ruby", "PHP",
            "HyperCard", "HyperTalk", "SuperCard", "MetaCard", "Revolution", "LiveCode", "Director",
            "Lingo", "Authorware", "Flash", "ActionScript", "Visual C++", "Visual J++", "Visual FoxPro",
            "PowerBuilder", "4GL", "Fourth Generation Language", "dBase", "dBase II", "dBase III", "dBase IV",
            "FoxPro", "FoxBASE", "Clipper", "Paradox", "Access", "FileMaker", "DataFlex", "Magic", "Clarion",
            "Alpha Four", "Alpha Five", "R:BASE", "Q&A", "PFS:File", "Framework", "Symphony", "Jazz",
            "Lotus 1-2-3", "Lotus 123", "Excel", "Multiplan", "VisiCalc", "SuperCalc", "Quattro", "Quattro Pro",
            "PlanPerfect", "As-Easy-As", "VP-Planner", "Twin", "Calc", "Gnumeric", "WordStar", "WordPerfect",
            "Microsoft Word", "Word for DOS", "Word for Windows", "DisplayWrite", "MultiMate", "Wang", "XyWrite",
            "Sprint", "PC-Write", "Professional Write", "PFS:Write", "First Choice", "Works", "Microsoft Works",
            "AppleWorks", "ClarisWorks", "Integrated", "Framework", "Symphony", "Jazz", "Open Access",
            "Enable", "Smart", "PFS:First Choice", "Better Working", "Eight-in-One", "AlphaWorks", "LotusWorks",
            "PerfectWorks", "Microsoft Office", "Office 97", "Office 2000", "Office XP", "Office 2003",
            "StarOffice", "OpenOffice", "LibreOffice", "Corel Office", "WordPerfect Office", "Lotus SmartSuite",
            "Desktop Publishing", "DTP", "PageMaker", "Ventura Publisher", "QuarkXPress", "FrameMaker",
            "Interleaf", "Ready,Set,Go!", "Publish-It!", "First Publisher", "Express Publisher", "Timeworks Publisher",
            "The Print Shop", "PrintMaster", "PrintShop", "Newsroom", "Certificate Maker", "Banner Maker",
            "Graphics Software", "Paint", "Draw", "CAD", "AutoCAD", "AutoCAD LT", "TurboCAD", "DesignCAD",
            "Generic CADD", "DataCAD", "MicroStation", "CADKEY", "Pro/ENGINEER", "SolidWorks", "Solid Edge",
            "CATIA", "Unigraphics", "I-DEAS", "Paint Shop Pro", "CorelDRAW", "Adobe Illustrator", "FreeHand",
            "Canvas", "Deneba Canvas", "MacDraw", "MacPaint", "SuperPaint", "PixelPaint", "Studio/8", "Studio/32",
            "Deluxe Paint", "DPaint", "Personal Paint", "Brilliance", "TV Paint", "Photon Paint", "DigiPaint",
            "Aegis Images", "Butcher", "GIMP", "Photoshop", "Photoshop Elements", "Paint.NET", "Krita",
            "3D Software", "3D Studio", "3D Studio Max", "3ds Max", "LightWave", "LightWave 3D", "Imagine",
            "Turbo Silver", "Sculpt 3D", "Sculpt 4D", "Caligari", "trueSpace", "POV-Ray", "Persistence of Vision",
            "RayDream", "Bryce", "Vue", "Terragen", "Moray", "Animation Master", "Hash Animation Master",
            "Aladdin 4D", "Real 3D", "Maxon Cinema 4D", "Cinema 4D", "Softimage", "Softimage 3D", "Softimage XSI",
            "Maya", "Alias", "Wavefront", "Houdini", "Blender", "Wings 3D", "Milkshape", "Metasequoia",
            "AC3D", "Amapi", "Carrara", "Hexagon", "Modo", "Silo", "ZBrush", "Mudbox", "Sculptris",
            "Music Software", "Tracker", "ProTracker", "OctaMED", "Med", "SoundTracker", "NoiseTracker",
            "FastTracker", "Impulse Tracker", "Scream Tracker", "ModPlug Tracker", "MilkyTracker", "Renoise",
            "MIDI Sequencer", "Cubase", "Logic", "Cakewalk", "Sonar", "Pro Tools", "Digital Performer",
            "Vision", "Studio Vision", "Performer", "Master Tracks", "Voyetra", "Sequencer Plus", "Dr. T's KCS",
            "Music-X", "Bars & Pipes", "Notator", "Creator", "FL Studio", "Fruity Loops", "Reason", "Ableton Live",
            "Acid", "Sound Forge", "WaveLab", "Cool Edit", "Adobe Audition", "Audacity", "GoldWave",
            "Video Software", "Video Toaster", "Video Toaster Flyer", "LightWave", "Aura", "Premiere",
            "Adobe Premiere", "Media 100", "Avid", "Final Cut", "Final Cut Pro", "iMovie", "Movie Maker",
            "Windows Movie Maker", "Pinnacle Studio", "VideoStudio", "Ulead VideoStudio", "Vegas", "Sony Vegas",
            "VEGAS Pro", "After Effects", "Combustion", "Shake", "Fusion", "Nuke", "DaVinci Resolve",
            "Utilities", "Norton Utilities", "Norton Commander", "PC Tools", "Central Point Software", "PC Tools Deluxe",
            "XTree", "XTreeGold", "XTreePro", "SpinRite", "Gibson Research", "Disk Doctor", "Speed Disk",
            "Defrag", "Defragmenter", "ScanDisk", "CHKDSK", "Format", "FDISK", "Partition Magic", "Drive Image",
            "Ghost", "Norton Ghost", "Acronis", "True Image", "Backup", "Backup Software", "PC Backup",
            "Fastback", "Colorado Backup", "Retrospect", "ARCserve", "BackupExec", "Veritas Backup Exec",
            "Compression", "PKZIP", "WinZip", "WinRAR", "ARJ", "LHA", "LZH", "StuffIt", "Compact Pro",
            "DiskDoubler", "Now Compress", "DriveSpace", "DoubleSpace", "Stacker", "SuperStor", "JAM",
            "Antivirus", "Anti-virus", "Virus Scanner", "Norton AntiVirus", "McAfee", "VirusScan", "Dr. Solomon's",
            "F-Prot", "F-Secure", "AVG", "Avast", "Avira", "Kaspersky", "Trend Micro", "PC-cillin", "Sophos",
            "ESET", "NOD32", "Panda", "Symantec", "Norton 360", "Norton Internet Security", "Zone Alarm",
            "Firewall", "Black Ice", "Tiny Firewall", "Kerio", "Outpost", "Comodo", "System Software",
            "Device Driver", "TSR", "Terminate and Stay Resident", "Memory Manager", "QEMM", "386MAX", "EMM386",
            "HIMEM.SYS", "Expanded Memory", "EMS", "Extended Memory", "XMS", "Upper Memory", "UMB", "HMA",
            "High Memory Area", "DOS Extender", "DOS/4GW", "Phar Lap", "Rational Systems", "DPMI", "VCPI",
            "Desqview", "Windows 386", "Multitasking", "Task Switching", "Time Sharing", "Virtual Memory",
            "Swap File", "Page File", "RAM Disk", "RAM Drive", "Cache", "Disk Cache", "SmartDrive", "SMARTDRV",
            "NCACHE", "Super PC-Kwik", "PC-Cache", "Lightning", "File Manager", "Program Manager", "Shell",
            "Command Shell", "4DOS", "NDOS", "Take Command", "PowerShell", "Terminal Emulator", "Communications Software",
            "Terminal Software", "ProComm", "ProComm Plus", "Telix", "Telemate", "Terminate", "HyperTerminal",
            "HyperACCESS", "CrossTalk", "Crosstalk", "Kermit", "MS-Kermit", "C-Kermit", "ZModem", "YModem",
            "XModem", "Kermit", "FTP", "File Transfer Protocol", "Telnet", "SSH", "Secure Shell", "PuTTY",
            "SecureCRT", "TeraTerm", "ZOC", "Reflection", "KEA", "EXTRA!", "Attachmate", "3270", "5250",
            "VT100", "VT220", "ANSI", "TTY", "BBS Software", "Bulletin Board System", "RemoteAccess", "RA",
            "Maximus", "Opus", "QuickBBS", "SuperBBS", "Telegard", "Renegade", "TAG", "WWIV", "PCBoard",
            "Wildcat", "Major BBS", "MajorBBS", "Galacticomm", "FirstClass", "Citadel", "GBBS", "RBBS",
            "Fido", "FidoNet", "FrontDoor", "BinkleyTerm", "Portal of Power", "POP", "InterMail", "D'Bridge",
            "Mailer", "Tosser", "Scanner", "Door", "Door Game", "Trade Wars", "Trade Wars 2002", "Legend of the Red Dragon",
            "LORD", "Usurper", "Barren Realms Elite", "BRE", "Solar Realms Elite", "SRE", "The Pit", "Food Fight",
            "Land of Devastation", "LOD", "Operation Overkill", "Overkill", "Planets TEOS", "TEOS", "VGA Planets"
        });

        // Games and Gaming
        tags.AddRange(new[]
        {
            "Gaming", "Retro Gaming", "Vintage Gaming", "Classic Gaming", "Arcade", "Arcade Game", "Coin-op",
            "Coin-operated", "Cabinet", "Arcade Cabinet", "JAMMA", "MAME", "Multiple Arcade Machine Emulator",
            "Neo Geo", "Neo Geo MVS", "Neo Geo AES", "Neo Geo CD", "CPS-1", "CPS-2", "CPS-3", "Naomi",
            "Model 1", "Model 2", "Model 3", "System 16", "System 32", "X-Board", "Y-Board", "Namco System 22",
            "Namco System 23", "Taito F3", "Konami GX", "Console", "Game Console", "Video Game Console",
            "Home Console", "Handheld", "Handheld Console", "Portable Console", "Atari 2600", "Atari 5200",
            "Atari 7800", "Atari Jaguar", "Atari Lynx", "Nintendo Entertainment System", "NES", "Famicom",
            "Super Nintendo", "SNES", "Super Famicom", "Nintendo 64", "N64", "GameCube", "Wii", "Wii U",
            "Nintendo Switch", "Game Boy", "Game Boy Color", "Game Boy Advance", "GBA", "Nintendo DS", "NDS",
            "Nintendo 3DS", "3DS", "Virtual Boy", "Sega Master System", "SMS", "Sega Genesis", "Mega Drive",
            "Sega CD", "Mega CD", "Sega 32X", "Sega Saturn", "Sega Dreamcast", "Game Gear", "Sega Nomad",
            "Sony PlayStation", "PS1", "PSX", "PlayStation 2", "PS2", "PlayStation 3", "PS3", "PlayStation 4",
            "PS4", "PlayStation 5", "PS5", "PlayStation Portable", "PSP", "PlayStation Vita", "PS Vita",
            "Microsoft Xbox", "Xbox", "Xbox 360", "Xbox One", "Xbox Series X", "Xbox Series S", "TurboGrafx-16",
            "PC Engine", "PC Engine CD", "TurboGrafx-CD", "SuperGrafx", "PC-FX", "3DO", "3DO Interactive Multiplayer",
            "CD-i", "Philips CD-i", "Amiga CD32", "Atari XEGS", "Amstrad GX4000", "Apple Pippin", "Bandai Pippin",
            "Casio Loopy", "Commodore 64 Games System", "C64GS", "FM Towns Marty", "Mattel Intellivision",
            "Intellivision", "Colecovision", "Coleco", "Magnavox Odyssey", "Odyssey", "Odyssey 2", "Vectrex",
            "GCE Vectrex", "Fairchild Channel F", "Bally Astrocade", "Emerson Arcadia 2001", "APF MP1000",
            "RCA Studio II", "Mattel Aquarius", "Action Max", "View-Master Interactive Vision", "Sega SG-1000",
            "Sega Mark III", "Wonder Swan", "Wonder Swan Color", "Neo Geo Pocket", "Neo Geo Pocket Color",
            "Atari Lynx", "Sega Game Gear", "TurboExpress", "PC Engine GT", "Gamate", "Mega Duck", "Cougar Boy",
            "Watara Supervision", "Game.com", "Tiger Game.com", "Gizmondo", "N-Gage", "Nokia N-Gage", "GP32",
            "GamePark GP32", "GP2X", "Pandora", "OpenPandora", "Dingoo", "Caanoo", "Wiz", "GP2X Wiz", "Zodiac",
            "Tapwave Zodiac", "Cybiko", "Pelican VG Pocket", "VG Pocket", "VG Pocket Max", "VG Pocket Caplet",
            "Mega Duck", "Cougar Boy", "Design Master Senario", "Game Wizard", "Game Fighter", "Pro Fighter",
            "Romtendo", "Retro Duo", "Retro Trio", "RetroN", "RetroN 5", "Retro Freak", "Polymega", "Analogue",
            "Analogue Nt", "Analogue Super Nt", "Analogue Mega Sg", "Analogue Pocket", "MiSTer", "MiST",
            "DE10-Nano", "FPGA", "Field Programmable Gate Array", "Flash Cart", "Flash Cartridge", "Everdrive",
            "SD2SNES", "FXPak", "PowerPak", "N8", "Mega Everdrive", "Turbo Everdrive", "Master Everdrive",
            "GB Everdrive", "GBA Everdrive", "64drive", "GDEMU", "PSIO", "MODE", "Terraonion", "Optical Drive Emulator",
            "ODE", "Modchip", "Modification Chip", "Softmod", "Homebrew", "Homebrew Software", "Homebrew Game",
            "ROM", "ROM Image", "ROM File", "ROM Dump", "ISO", "ISO Image", "BIN/CUE", "CHD", "MAME ROM",
            "No-Intro", "Redump", "TOSEC", "GoodTools", "GoodROM", "GoodSNES", "GoodGen", "GoodGBA",
            "Emulator", "Emulation", "Accuracy", "Cycle-accurate", "ZSNES", "SNES9x", "bsnes", "higan", "Mesen",
            "FCEUX", "Nestopia", "puNES", "Genesis Plus", "Kega Fusion", "Gens", "BlastEm", "Project64",
            "Mupen64", "1964", "Dolphin", "PCSX2", "ePSXe", "Mednafen", "RetroArch", "Libretro", "BizHawk",
            "OpenEmu", "MAME", "FinalBurn", "FinalBurn Alpha", "FinalBurn Neo", "WinUAE", "FS-UAE", "UAE",
            "Vice", "CCS64", "Hoxs64", "Stella", "ProSystem", "Handy", "Lynx Emulator", "VBA", "VisualBoyAdvance",
            "mGBA", "DeSmuME", "melonDS", "Citra", "Yuzu", "Ryujinx", "PPSSPP", "PCSX", "Duckstation", "ePSXe",
            "Bleem!", "Connectix Virtual Game Station", "VGS", "PCSX2", "RPCS3", "Xenia", "Cemu", "Yuzu",
            "Ryujinx", "Game Preservation", "Preservation", "Archival", "Digital Preservation", "Physical Media",
            "Cartridge", "Cart", "HuCard", "Game Card", "Game Pak", "Memory Card", "Save Data", "Battery Backup",
            "SRAM", "Save State", "Cheat Code", "Game Genie", "Game Shark", "GameShark", "Action Replay",
            "Pro Action Replay", "Code Breaker", "Xploder", "Xplorer", "ROM Hack", "ROM Hacking", "Translation",
            "Fan Translation", "Reproduction", "Repro Cart", "Reproduction Cartridge", "Clone Console",
            "Famiclone", "Dendy", "Pegasus", "PolyStation", "POP Station", "Ending Man", "Terminator",
            "Super Megason", "Creation", "Family Game", "Micro Genius", "2600 Clone", "Atari Clone",
            "ColecoVision Clone", "Intellivision Clone", "Bit Corporation", "Gamate", "CreatiVision",
            "Dynavision", "Rambo", "Phantom System", "Action Gaming System", "Zoga", "Sorrent", "SG-1000 II"
        });

        // Documentation and Manuals
        tags.AddRange(new[]
        {
            "Manual", "User Manual", "Owner's Manual", "Operating Manual", "Instruction Manual", "Reference Manual",
            "Service Manual", "Technical Manual", "Repair Manual", "Maintenance Manual", "Programming Manual",
            "Installation Guide", "Setup Guide", "Quick Start Guide", "Getting Started", "User Guide",
            "Administrator Guide", "System Administrator", "Programmer's Guide", "Developer Guide", "API Reference",
            "Technical Reference", "Hardware Reference", "Software Reference", "Command Reference", "Language Reference",
            "BIOS Reference", "ROM Listing", "Schematic", "Circuit Diagram", "Wiring Diagram", "Block Diagram",
            "Flow Chart", "Flowchart", "Data Sheet", "Datasheet", "Specification", "Tech Specs", "Technical Specifications",
            "Pinout", "Pin Configuration", "Memory Map", "I/O Map", "Port Map", "Register Map", "Interrupt Vector",
            "System Architecture", "White Paper", "Technical Note", "Application Note", "Design Note", "Errata",
            "Addendum", "Supplement", "Update", "Revision", "Version History", "Change Log", "Release Notes",
            "Compatibility List", "HCL", "Hardware Compatibility List", "Driver Disk", "Driver Diskette",
            "Utility Disk", "Diagnostic Disk", "System Disk", "Boot Disk", "Recovery Disk", "Restore Disk",
            "Installation Disk", "Setup Disk", "Program Disk", "Data Disk", "Documentation", "Docs", "Help File",
            "Help System", "Online Help", "Context-sensitive Help", "Readme", "Read Me", "README.TXT", "FAQ",
            "Frequently Asked Questions", "Tutorial", "How-to", "Walkthrough", "Tips and Tricks", "Cheat Sheet",
            "Quick Reference", "Reference Card", "Keyboard Template", "Command Card", "Function Key Template",
            "Certificate of Authenticity", "COA", "License", "License Agreement", "EULA", "Registration Card",
            "Warranty Card", "Warranty", "Support", "Technical Support", "Customer Support", "Phone Support",
            "BBS Support", "Online Support", "CompuServe", "GEnie", "AOL", "Prodigy", "Delphi", "The Source",
            "User Group", "Newsletter", "Magazine", "Byte Magazine", "PC Magazine", "PC World", "Computer Shopper",
            "InfoWorld", "Computerworld", "Dr. Dobb's Journal", "DDJ", "Creative Computing", "Compute!",
            "Compute!'s Gazette", "RUN", "Ahoy!", "Transactor", "Micro", "80 Micro", "inCider", "A+", "Nibble",
            "Call-A.P.P.L.E.", "Softalk", "Hardcore Computist", "Computist", "Antic", "Analog", "Page 6",
            "ST-Log", "STart", "Amiga World", "Amazing Computing", "Amiga Format", "Amiga Power", "Amiga User International",
            "Commodore User", "Zzap!64", "Your Sinclair", "Sinclair User", "ZX Computing", "Crash", "Your Spectrum",
            "Amstrad Action", "Amstrad Computer User", "ACU", "Computing Today", "Electronics Today", "ETI",
            "Radio-Electronics", "Popular Electronics", "Electronics Now", "Circuit Cellar", "Nuts and Volts",
            "Elektor", "Practical Electronics", "Everyday Electronics", "EPE", "Silicon Chip", "Wireless World",
            "Ham Radio", "QST", "73 Magazine", "CQ", "Book", "Programming Book", "Reference Book", "Textbook",
            "Guide Book", "Handbook", "Pocket Guide", "Field Guide", "Bible", "Black Book", "Red Book", "Blue Book",
            "Green Book", "White Book", "Orange Book", "Yellow Book", "Rainbow Series", "Authorized Guide",
            "Official Guide", "Unofficial Guide", "Inside", "Undocumented", "Secrets", "Hacks", "Tips", "Tricks",
            "Advanced", "Professional", "Mastering", "Learning", "Beginning", "Introduction", "Fundamentals",
            "Essentials", "Complete", "Comprehensive", "Definitive", "Ultimate", "Encyclopedia", "Dictionary",
            "Glossary", "Thesaurus", "Atlas", "Almanac", "Catalog", "Catalogue", "Directory", "Index", "Bibliography"
        });

        // Collectible Conditions and Attributes
        tags.AddRange(new[]
        {
            "New", "Mint", "Near Mint", "Excellent", "Very Good", "Good", "Fair", "Poor", "New Old Stock", "NOS",
            "Sealed", "Factory Sealed", "Shrink Wrapped", "Unopened", "Complete", "Complete in Box", "CIB",
            "Boxed", "Loose", "Cart Only", "Disc Only", "Manual Included", "Missing Manual", "Missing Box",
            "Box Damage", "Label Damage", "Sunfade", "Sun Fading", "Yellowing", "Discoloration", "Working",
            "Non-working", "For Parts", "Parts Only", "Tested", "Untested", "Refurbished", "Restored",
            "Recapped", "Modified", "Modded", "Stock", "Original", "Authentic", "Genuine", "Reproduction",
            "Bootleg", "Counterfeit", "Pirate", "Aftermarket", "Third Party", "OEM", "Original Equipment",
            "Retail", "Bundle", "Pack-in", "Promotional", "Demo", "Not for Resale", "NFR", "Review Copy",
            "Press Kit", "Developer Kit", "Dev Kit", "Prototype", "Beta", "Alpha", "Pre-release", "Unreleased",
            "Cancelled", "Sample", "Engineering Sample", "ES", "Qualification Sample", "QS", "Retail Sample",
            "Production Sample", "PAL", "NTSC", "SECAM", "NTSC-J", "NTSC-U", "PAL-A", "PAL-B", "PAL-G",
            "PAL-I", "PAL-M", "PAL-N", "Region Free", "Multi-region", "Import", "Domestic", "North America",
            "Europe", "Japan", "Asia", "Australia", "World", "Limited Edition", "Special Edition", "Collector's Edition",
            "Anniversary Edition", "Signature Edition", "Signed", "Autographed", "Numbered", "Serial Number",
            "First Edition", "First Print", "First Run", "Launch Edition", "Day One Edition", "Revision",
            "Rev A", "Rev B", "Version", "Variant", "Black Label", "Greatest Hits", "Player's Choice",
            "Platinum", "Essentials", "Classics", "Value", "Budget", "Kixx", "Hit Squad", "Mastertronic",
            "Alternative", "Ricochet", "Sold Out", "Xplosiv", "White Label", "Green Pepper", "Yellow Tab",
            "PC Best", "Purple Hills", "Re-release", "Reissue", "Reprint", "Enhanced", "Deluxe", "Gold",
            "Platinum", "Diamond", "Complete", "Ultimate", "Definitive", "HD", "Remaster", "Remake", "Port",
            "Conversion", "Translation", "Localization", "Rental", "Rental Version", "Blockbuster Exclusive",
            "Store Exclusive", "Pre-order Bonus", "Mail Order", "Club Nintendo", "Nintendo Power", "Subscribers",
            "Members Only", "Convention Exclusive", "E3", "CES", "Comdex", "Tokyo Game Show", "TGS", "Gamescom",
            "PAX", "Comic-Con", "Tournament Edition", "Championship", "Competition", "Contest", "Prize",
            "Trophy", "Award", "Gold Cart", "Gray Cart", "Black Cart", "Red Cart", "Blue Cart", "Green Cart",
            "Yellow Cart", "Clear Cart", "Transparent", "Translucent", "Glow in the Dark", "Holographic",
            "Lenticular", "3D Cover", "Embossed", "Foil", "Metallic", "Chrome", "Prismatic", "Big Box",
            "Small Box", "DVD Case", "Jewel Case", "Cardboard Box", "Clamshell", "Slipcase", "Steelbook",
            "Tin Box", "Wooden Box", "Collector's Box", "Display Box", "Storage Box", "Protective Case",
            "Game Case", "Universal Game Case", "UGC", "BitBox", "Custom Case", "Replacement Case", "Memorabilia",
            "Promotional Item", "Promo", "Swag", "Merchandise", "T-shirt", "Poster", "Sticker", "Button",
            "Pin", "Badge", "Keychain", "Figure", "Statue", "Plush", "Toy", "Model", "Replica", "Standee",
            "Display", "Sign", "Banner", "Flag", "Soundtrack", "OST", "Art Book", "Strategy Guide", "Guide Book",
            "Novel", "Comic", "Manga", "Trading Card", "Card Game", "Board Game", "Tabletop", "Pen and Paper",
            "RPG", "Role Playing Game", "Miniature", "Dice", "Coin", "Token", "Chip", "Medal", "Certificate",
            "Coupon", "Voucher", "Ticket", "Pass", "VIP", "Backstage", "Press Pass", "Media Kit", "EPK",
            "Electronic Press Kit", "One Sheet", "Sell Sheet", "Brochure", "Flyer", "Advertisement", "Ad",
            "Print Ad", "Marketing", "Point of Sale", "POS", "POP", "Standee", "Floor Display", "Counter Display",
            "Shelf Talker", "Wobbler", "Dangler", "Window Cling", "Decal", "Vinyl", "Static Cling", "Magnet",
            "Mouse Pad", "Coaster", "Mug", "Glass", "Plate", "Lithograph", "Cel", "Animation Cel", "Production Art",
            "Concept Art", "Sketch", "Original Art", "Print", "Giclee", "Screen Print", "Serigraph", "Etching",
            "Engraving", "Woodcut", "Letterpress", "Offset", "Digital Print", "Photo", "Photograph", "Slide",
            "Transparency", "Negative", "Contact Sheet", "Proof", "Test Print", "Artist Proof", "AP", "Printer's Proof",
            "PP", "Publisher's Proof", "HC", "Hors Commerce", "Remarque", "Hand Colored", "Hand Finished",
            "Embellished", "Mixed Media", "Original", "One of a Kind", "OOAK", "Custom", "Commission", "Fan Art"
        });

        // Sale Status Tags
        tags.AddRange(new[]
        {
            "For Sale", "To Be Sold", "Not For Sale", "Sold", "Reserved", "On Hold", "Available",
            "Pending Sale", "Listed", "Unlisted", "Make Offer", "Trade Only", "Display Only",
            "Museum Piece", "Private Collection", "Offers Welcome", "Price Negotiable", "Firm Price",
            "Auction Item", "Buy It Now", "Starting Bid", "Reserve Met", "No Reserve"
        });

        // Repair Status Tags
        tags.AddRange(new[]
        {
            "Needs Repair", "Awaiting Parts", "In Repair", "Repair In Progress", "Partially Working",
            "Boots But Issues", "Powers On Only", "No Power", "Capacitor Issues", "Needs Recap",
            "Battery Damage", "Battery Leak", "Corrosion Damage", "Water Damage", "Physical Damage",
            "Cracked Case", "Missing Parts", "Spare Parts Included", "Documentation Included",
            "Professionally Serviced", "DIY Repair", "Beyond Repair", "For Reference Only",
            "Static Display", "Working Display", "Intermittent Issues", "Video Issues", "Audio Issues",
            "Keyboard Issues", "Drive Issues", "PSU Issues", "Power Supply Issues", "Monitor Issues",
            "Screen Burn-in", "Dead Pixels", "Lines on Screen", "No Video", "No Audio", "Garbled Graphics",
            "Memory Issues", "RAM Issues", "ROM Issues", "Chip Issues", "Socket Issues", "Trace Repair",
            "Board Repair", "Retrobrighted", "Case Mod", "Paint Damage", "Smoke Damage", "UV Damage",
            "Heat Damage", "Cold Damage", "Shipping Damage", "Previous Repair Attempt", "Bad Repair",
            "Needs Cleaning", "Deep Cleaned", "Ultrasonic Cleaned", "Contact Cleaned", "Lubricated"
        });

        // Project Status Tags
        tags.AddRange(new[]
        {
            "Project Machine", "Restoration Project", "Future Project", "Completed Project",
            "Abandoned Project", "Long Term Project", "Weekend Project", "Winter Project",
            "Summer Project", "Ongoing Project", "Stalled Project", "Priority Project",
            "Back Burner Project", "Group Project", "Community Project", "Learning Project",
            "First Project", "Practice Project", "Parts Donor", "Donor Machine", "Parts Source",
            "Upgrade Project", "Mod Project", "Preservation Project", "Documentation Project"
        });

        // Handheld Devices and PDAs
        tags.AddRange(new[]
        {
            "Handheld", "PDA", "Personal Digital Assistant", "Pocket Computer", "Palmtop",
            "Palm", "Palm Pilot", "PalmPilot", "Palm III", "Palm IIIx", "Palm V", "Palm Vx",
            "Palm m100", "Palm m105", "Palm m125", "Palm m130", "Palm m500", "Palm m505", "Palm m515",
            "Palm Tungsten", "Tungsten T", "Tungsten T2", "Tungsten T3", "Tungsten T5", "Tungsten E",
            "Tungsten E2", "Tungsten C", "Tungsten W", "Palm Zire", "Zire 21", "Zire 31", "Zire 71",
            "Zire 72", "Palm TX", "Palm LifeDrive", "Palm Centro", "Palm Pre", "Palm Pixi",
            "Handspring", "Handspring Visor", "Visor Deluxe", "Visor Platinum", "Visor Prism",
            "Visor Edge", "Visor Pro", "Visor Neo", "Springboard", "Handspring Treo", "Treo 90",
            "Treo 180", "Treo 180g", "Treo 270", "Treo 300", "Treo 600", "Treo 650", "Treo 680",
            "Treo 700", "Treo 700p", "Treo 700w", "Treo 700wx", "Treo 750", "Treo 755p", "Treo 800w",
            "Sony CLIE", "CLIE PEG", "PEG-N Series", "PEG-S Series", "PEG-T Series", "PEG-NR Series",
            "PEG-NX Series", "PEG-NZ Series", "PEG-SJ Series", "PEG-TG Series", "PEG-TH Series",
            "PEG-TJ Series", "PEG-UX Series", "PEG-VZ Series", "CLIE Memory Stick",
            "HP iPAQ", "Compaq iPAQ", "iPAQ H1900", "iPAQ H2200", "iPAQ H3100", "iPAQ H3600",
            "iPAQ H3700", "iPAQ H3800", "iPAQ H3900", "iPAQ H4100", "iPAQ H4300", "iPAQ H4700",
            "iPAQ H5100", "iPAQ H5400", "iPAQ H5500", "iPAQ H6300", "iPAQ H6500", "iPAQ RX",
            "iPAQ RX1950", "iPAQ RX3000", "iPAQ RX3100", "iPAQ RX3400", "iPAQ RX3700", "iPAQ RX4200",
            "iPAQ RX5000", "iPAQ RX5700", "iPAQ RX5900", "iPAQ HX", "iPAQ HX2000", "iPAQ HX2100",
            "iPAQ HX2400", "iPAQ HX2700", "iPAQ HX2750", "iPAQ HX2790", "iPAQ HX4700",
            "HP Jornada", "Jornada 420", "Jornada 430", "Jornada 520", "Jornada 540", "Jornada 545",
            "Jornada 547", "Jornada 548", "Jornada 560", "Jornada 565", "Jornada 567", "Jornada 568",
            "Jornada 680", "Jornada 690", "Jornada 710", "Jornada 720", "Jornada 728", "Jornada 820",
            "Dell Axim", "Axim X3", "Axim X30", "Axim X5", "Axim X50", "Axim X50v", "Axim X51",
            "Axim X51v", "Pocket PC", "Windows CE", "Windows Mobile", "Windows Mobile 2003",
            "Windows Mobile 5", "Windows Mobile 6", "Windows Mobile 6.1", "Windows Mobile 6.5",
            "Palm OS", "Palm OS 1", "Palm OS 2", "Palm OS 3", "Palm OS 4", "Palm OS 5", "Garnet OS",
            "Psion", "Psion Organiser", "Psion Organiser I", "Psion Organiser II", "Psion Series 3",
            "Psion Series 3a", "Psion Series 3c", "Psion Series 3mx", "Psion Series 5", "Psion Series 5mx",
            "Psion Series 7", "Psion Revo", "Psion Revo Plus", "Psion netBook", "Psion netPad",
            "Psion Wavefinder", "EPOC", "EPOC32", "Symbian", "Sharp Wizard", "Sharp Zaurus",
            "Zaurus SL-5000", "Zaurus SL-5500", "Zaurus SL-5600", "Zaurus SL-6000", "Zaurus SL-C700",
            "Zaurus SL-C750", "Zaurus SL-C760", "Zaurus SL-C860", "Zaurus SL-C1000", "Zaurus SL-C3000",
            "Zaurus SL-C3100", "Zaurus SL-C3200", "Casio BOSS", "Casio Cassiopeia", "Cassiopeia A-10",
            "Cassiopeia A-11", "Cassiopeia A-20", "Cassiopeia E-10", "Cassiopeia E-11", "Cassiopeia E-100",
            "Cassiopeia E-105", "Cassiopeia E-115", "Cassiopeia E-125", "Cassiopeia E-200", "Cassiopeia E-500",
            "Cassiopeia E-700", "Cassiopeia E-750", "Cassiopeia EM-500", "Casio Pocket Viewer",
            "Apple Newton", "Newton MessagePad", "MessagePad 100", "MessagePad 110", "MessagePad 120",
            "MessagePad 130", "MessagePad 2000", "MessagePad 2100", "eMate 300", "Newton OS",
            "TRS-80 Pocket Computer", "PC-1", "PC-2", "PC-3", "PC-4", "PC-5", "PC-6", "PC-7", "PC-8",
            "Sharp PC-1211", "Sharp PC-1250", "Sharp PC-1251", "Sharp PC-1260", "Sharp PC-1261",
            "Sharp PC-1262", "Sharp PC-1350", "Sharp PC-1360", "Sharp PC-1401", "Sharp PC-1403",
            "Sharp PC-1500", "Sharp PC-1600", "Sharp PC-2500", "Sharp PC-E220", "Sharp PC-E500",
            "Sharp PC-G850", "Casio PB-100", "Casio PB-110", "Casio PB-200", "Casio PB-300",
            "Casio PB-400", "Casio PB-410", "Casio PB-500", "Casio PB-700", "Casio PB-770",
            "Casio PB-1000", "Casio PB-2000", "Casio FX-700P", "Casio FX-702P", "Casio FX-710P",
            "Casio FX-720P", "Casio FX-730P", "Casio FX-750P", "Casio FX-770P", "Casio FX-780P",
            "Casio FX-785P", "Casio FX-790P", "Casio FX-795P", "Casio FX-850P", "Casio FX-880P",
            "Casio FX-890P", "Casio VX-4", "Casio Z-1", "Casio Z-1GR", "HP 95LX", "HP 100LX",
            "HP 200LX", "HP 300LX", "HP 320LX", "HP 360LX", "HP 620LX", "HP 660LX", "HP 690",
            "HP 700LX", "HP 1000CX", "HP OmniGo", "OmniGo 100", "OmniGo 120", "OmniGo 700LX",
            "Atari Portfolio", "Poqet PC", "Poqet PC Classic", "Poqet PC Prime", "Poqet PC Plus",
            "Cambridge Z88", "Amstrad PenPad", "Amstrad NC100", "Amstrad NC150", "Amstrad NC200",
            "Tandy WP-2", "NEC MobilePro", "MobilePro 200", "MobilePro 400", "MobilePro 450",
            "MobilePro 700", "MobilePro 750", "MobilePro 770", "MobilePro 780", "MobilePro 790",
            "MobilePro 800", "MobilePro 880", "MobilePro 900", "NEC PC-8201", "NEC PC-8300",
            "Philips Nino", "Nino 200", "Nino 300", "Nino 500", "Velo 1", "Velo 500",
            "Everex Freestyle", "Toshiba Libretto", "Libretto 20", "Libretto 50", "Libretto 70",
            "Libretto 100", "Libretto 110", "Libretto U100", "IBM WorkPad", "WorkPad z50",
            "Franklin eBookMan", "Rex 3000", "Rex 5000", "Rex 6000", "DataRover 840",
            "Cybiko", "Cybiko Classic", "Cybiko Xtreme", "AlphaSmart", "AlphaSmart 2000",
            "AlphaSmart 3000", "Dana", "Dana Wireless", "Neo", "Neo 2"
        });

        // Vintage Calculators
        tags.AddRange(new[]
        {
            "Calculator", "Scientific Calculator", "Programmable Calculator", "Graphing Calculator",
            "RPN Calculator", "Reverse Polish Notation", "Algebraic Calculator", "Financial Calculator",
            "HP Calculator", "HP-35", "HP-41", "HP-41C", "HP-41CV", "HP-41CX", "HP-42S", "HP-48",
            "HP-48G", "HP-48GX", "HP-48S", "HP-48SX", "HP-49", "HP-49G", "HP-50G", "HP-65", "HP-67",
            "HP-71B", "HP-75", "HP-97", "HP-10C", "HP-11C", "HP-12C", "HP-15C", "HP-16C", "HP-19C",
            "HP-25", "HP-25C", "HP-28C", "HP-28S", "HP-32S", "HP-32SII", "HP-33S", "HP-34C", "HP-38G",
            "HP-39G", "HP-40G", "HP Prime", "HP-45", "HP-55", "HP-80", "HP-91", "HP-92", "HP-95C",
            "Texas Instruments Calculator", "TI Calculator", "TI-30", "TI-35", "TI-36", "TI-55", "TI-57",
            "TI-58", "TI-58C", "TI-59", "TI-74", "TI-81", "TI-82", "TI-83", "TI-83 Plus", "TI-84",
            "TI-84 Plus", "TI-85", "TI-86", "TI-89", "TI-89 Titanium", "TI-92", "TI-92 Plus", "TI-95",
            "TI Voyage 200", "TI-Nspire", "TI-Nspire CAS", "TI-Nspire CX", "SR-50", "SR-51", "SR-52",
            "SR-56", "TI-2500", "TI Datamath", "TI Little Professor", "TI Speak & Spell",
            "Speak & Math", "Speak & Read", "TI Business Analyst", "TI MBA", "TI-5100", "TI-5200",
            "Casio Calculator", "Casio FX", "FX-1", "FX-10", "FX-39", "FX-82", "FX-115", "FX-260",
            "FX-300", "FX-451", "FX-502P", "FX-602P", "FX-603P", "FX-7000G", "FX-7500G", "FX-8000G",
            "FX-8500G", "FX-9700G", "FX-9750G", "FX-9860G", "Casio ClassPad", "Casio Algebra FX",
            "Casio CFX-9850G", "Casio CFX-9950G", "Casio FX-CG10", "Casio FX-CG20", "Casio FX-CG50",
            "Casio PB-80", "Casio PB-88", "Casio CM-100", "Casio SL-1", "Casio Mini", "Casio AL-1000",
            "Casio AL-2000", "Casio FX-1000", "Casio FX-2000", "Casio FX-3000", "Casio FX-4000",
            "Casio FX-5000", "Casio FX-6000", "Casio FX-7000", "Casio FX-8000", "Casio FX-9000",
            "Sharp Calculator", "Sharp EL", "EL-5100", "EL-5150", "EL-5200", "EL-5250", "EL-5500",
            "EL-6200", "EL-8", "EL-8M", "EL-9000", "EL-9200", "EL-9300", "EL-9400", "EL-9600",
            "EL-9900", "Sharp PC-1200", "Sharp PC-1210", "Sharp PC-1246", "Sharp PC-1247", "Sharp PC-1248",
            "Sharp PC-1280", "Sharp PC-1285", "Sharp PC-1421", "Sharp PC-1430", "Sharp PC-1450",
            "Sharp PC-1460", "Sharp PC-1470", "Sharp PC-1475", "Sharp PC-1490", "Sharp PC-1500A",
            "Sharp EL-506", "Sharp EL-509", "Sharp EL-520", "Sharp EL-531", "Sharp EL-545", "Sharp EL-546",
            "Canon Calculator", "Canon Pocketronic", "Canon F-1", "Canon F-2", "Canon F-3", "Canon F-4",
            "Canon F-5", "Canon F-6", "Canon F-7", "Canon F-8", "Canon F-9", "Canon F-10", "Canon F-20",
            "Canon F-30", "Canon F-50", "Canon F-73", "Canon F-73P", "Canon F-300", "Canon F-500",
            "Canon F-600", "Canon F-700", "Canon F-800", "Canon X-07", "Canon X-1", "Canon X-2",
            "Sinclair Calculator", "Sinclair Executive", "Sinclair Cambridge", "Sinclair Scientific",
            "Sinclair Oxford", "Sinclair Sovereign", "Sinclair Wrist Calculator", "Commodore Calculator",
            "Commodore SR-36", "Commodore SR-37", "Commodore SR-38", "Commodore SR-1400", "Commodore SR-1800",
            "Commodore SR-4120", "Commodore SR-4148", "Commodore SR-4190", "Commodore SR-4912",
            "Commodore SR-5120", "Commodore SR-5148", "Commodore SR-5190", "Commodore SR-9190",
            "Commodore N60", "Commodore P50", "Commodore PR100", "Commodore S61", "Commodore US*8",
            "Monroe Calculator", "Monroe Epic", "Monroe 1655", "Monroe 1665", "Monroe 1785", "Monroe 1880",
            "Olivetti Calculator", "Olivetti Logos", "Olivetti Divisumma", "Olivetti P101", "Olivetti P602",
            "Olivetti P603", "Olivetti P652", "Olivetti P6040", "Olivetti P6060", "Olivetti Programma",
            "Victor Calculator", "Victor Comptometer", "Facit Calculator", "Friden Calculator",
            "Marchant Calculator", "Wang Calculator", "Wang 700", "Wang 720", "Wang 2200", "Wang 500",
            "Wang 600", "Busicom Calculator", "Busicom 141-PF", "Bowmar Calculator", "Bowmar 901B",
            "Craig Calculator", "Lloyd's Calculator", "National Semiconductor Calculator", "Novus Calculator",
            "Novus Mathematician", "Novus 650", "Novus 850", "Novus 4510", "Novus 4520", "Privileg Calculator",
            "Rockwell Calculator", "Sanyo Calculator", "Sanyo CZ", "Teal Calculator", "Teal LC811",
            "Unitrex Calculator", "Calculator Watch", "Calculator Pen", "Credit Card Calculator",
            "Desktop Calculator", "Pocket Calculator", "Printing Calculator", "Adding Machine",
            "Nixie Tube Calculator", "VFD Calculator", "LED Calculator", "LCD Calculator",
            "Solar Calculator", "Battery Calculator", "Mechanical Calculator", "Electronic Calculator",
            "Slide Rule", "Abacus", "Comptometer", "Curta Calculator"
        });

        // Handheld Gaming Devices
        tags.AddRange(new[]
        {
            "Handheld Game", "Portable Game", "LCD Game", "LED Game", "VFD Game", "Game & Watch",
            "Nintendo Game & Watch", "Game Boy", "Game Boy Original", "DMG", "Game Boy Pocket",
            "Game Boy Light", "Game Boy Color", "GBC", "Game Boy Advance", "GBA", "GBA SP",
            "Game Boy Advance SP", "Game Boy Micro", "Nintendo DS", "DS Lite", "DSi", "DSi XL",
            "Nintendo 3DS", "3DS XL", "New 3DS", "New 3DS XL", "2DS", "New 2DS XL", "Nintendo Switch",
            "Switch Lite", "Sega Game Gear", "Sega Nomad", "Atari Lynx", "Lynx I", "Lynx II",
            "Wonderswan", "Wonderswan Color", "SwanCrystal", "Neo Geo Pocket", "Neo Geo Pocket Color",
            "NGPC", "TurboExpress", "PC Engine GT", "Supervision", "Watara Supervision", "Game.com",
            "Tiger Game.com", "Gizmondo", "GP32", "GP2X", "GP2X Wiz", "GP2X Caanoo", "Pandora",
            "OpenPandora", "Dingoo", "Dingoo A320", "Dingoo A330", "Dingoo A380", "JXD", "GCW Zero",
            "PlayStation Portable", "PSP", "PSP-1000", "PSP-2000", "PSP-3000", "PSP Go", "PSP Street",
            "PlayStation Vita", "PS Vita", "PS Vita Slim", "PlayStation TV", "Microvision",
            "Milton Bradley Microvision", "Entex Adventure Vision", "Epoch Game Pocket Computer",
            "Epoch Barcode Battler", "Mega Duck", "Cougar Boy", "Gamate", "Bit Corporation Gamate",
            "Design Master Senshi", "Tiger Electronics", "Tiger LCD Game", "Tiger R-Zone", "R-Zone",
            "Tiger Electronics Handheld", "Konami Handheld", "Coleco Handheld", "Mattel Handheld",
            "Mattel Football", "Mattel Baseball", "Mattel Basketball", "Mattel Hockey", "Mattel Soccer",
            "Mattel Auto Race", "Mattel Armor Battle", "Bandai Handheld", "Bandai LCD Game",
            "Tomy Handheld", "Tomy LCD Game", "VTech Handheld", "VTech LCD Game", "Merlin",
            "Parker Brothers Merlin", "Simon", "Milton Bradley Simon", "Simon Says", "Speak & Spell",
            "Electronic Quarterback", "Electronic Detective", "Stop Thief", "Dark Tower", "Big Trak",
            "2-XL", "2-XL Robot", "Teddy Ruxpin", "Alphie", "Alphie Robot", "Little Professor",
            "Quiz Wiz", "Brain Bash", "Jeopardy Handheld", "Wheel of Fortune Handheld",
            "Tiger Electronics Handheld Game", "Double Dragon Handheld", "Street Fighter Handheld",
            "Mortal Kombat Handheld", "Sonic Handheld", "Power Rangers Handheld", "TMNT Handheld",
            "Batman Handheld", "Spider-Man Handheld", "X-Men Handheld", "Star Wars Handheld",
            "Pokemon Handheld", "Digimon Handheld", "Tamagotchi", "Virtual Pet", "Giga Pet",
            "Nano Pet", "Digital Pet", "Pocket Pikachu", "Pokemon Pikachu", "Pokéwalker",
            "Digivice", "Scannerz", "Radica Games", "Radica Handheld", "Jakks Pacific", "TV Games",
            "Plug and Play", "Leapster", "LeapFrog Leapster", "Leapster Explorer", "LeapPad",
            "Didj", "Leapster L-Max", "V.Smile", "VTech V.Smile", "V.Smile Pocket", "V.Motion",
            "Mobigo", "InnoTab", "Storio", "Cybiko Classic", "Cybiko Xtreme", "Tapwave Zodiac",
            "Zodiac 1", "Zodiac 2", "N-Gage", "Nokia N-Gage", "N-Gage QD", "Xperia Play",
            "Sony Ericsson Xperia Play", "Shield Portable", "Nvidia Shield Portable"
        });

        // Electronic Organizers and Digital Diaries
        tags.AddRange(new[]
        {
            "Electronic Organizer", "Digital Diary", "Electronic Dictionary", "Electronic Translator",
            "Electronic Address Book", "Electronic Calendar", "Electronic Notebook", "Digital Assistant",
            "Sharp Wizard", "OZ-7000", "OZ-7200", "OZ-8000", "OZ-8200", "OZ-9500", "OZ-9600",
            "IQ-7000", "IQ-8000", "IQ-8100", "IQ-8200", "IQ-8300", "IQ-8500", "IQ-8900", "IQ-9000",
            "Sharp YO", "YO-100", "YO-110", "YO-120", "YO-130", "YO-140", "YO-150", "YO-160",
            "YO-170", "YO-180", "YO-190", "YO-200", "YO-210", "YO-220", "YO-230", "YO-240",
            "Casio BOSS", "SF-3000", "SF-3300", "SF-3500", "SF-3600", "SF-3700", "SF-3900",
            "SF-4000", "SF-4300", "SF-4500", "SF-4600", "SF-4700", "SF-4900", "SF-5000",
            "SF-5100", "SF-5300", "SF-5500", "SF-5700", "SF-5900", "SF-6000", "SF-6300",
            "SF-6500", "SF-6700", "SF-6900", "SF-7000", "SF-7100", "SF-7200", "SF-7300",
            "SF-7500", "SF-7700", "SF-7900", "SF-8000", "SF-8350", "SF-9000", "SF-9300",
            "SF-9500", "SF-9700", "SF-M10", "SF-R10", "SF-R20", "Casio Data Bank",
            "Data Bank 50", "Data Bank 100", "Data Bank 150", "Data Bank 200", "Data Bank 300",
            "Casio Secret Sender", "Casio Digital Diary", "Casio Business Navigator", "BN-10",
            "BN-20", "BN-30", "BN-40", "Texas Instruments Organizer", "TI PS-6000", "PS-6100",
            "PS-6200", "PS-6300", "PS-6400", "PS-6500", "PS-6600", "PS-6700", "PS-6800",
            "TI Avigo", "Avigo 10", "Avigo 100", "Franklin Organizer", "Franklin Planner",
            "Franklin REX", "REX 3000", "REX 5000", "REX 6000", "Franklin Bookman", "Franklin eBookMan",
            "Franklin Language Master", "Franklin Spelling Ace", "Seiko Organizer", "Seiko DataGraph",
            "Seiko Data-2000", "Seiko DF-2000", "Seiko DF-3000", "Seiko IntelliLink", "Seiko Ruputer",
            "Seiko SmartPad", "Seiko MessageWatch", "Citizen DataSlim", "Citizen Digital Diary",
            "Citizen Pocket Mate", "Royal Organizer", "Royal DM70", "Royal DM80", "Royal DM90",
            "Oregon Scientific Organizer", "Amstrad Organiser", "Amstrad PDA600", "Matsushita Organizer",
            "Philips Organizer", "Canon Organizer", "Canon ZX-1", "Canon ZX-2", "Canon ZX-3",
            "Olivetti Organizer", "Rolodex Organizer", "Rolodex Electrodex", "Rolodex Electronics",
            "AT&T Organizer", "Bell South Organizer", "Radio Shack Organizer", "EC-256", "EC-290",
            "EC-309", "EC-310", "EC-312", "EC-319", "EC-320", "EC-330", "EC-340", "EC-350",
            "EC-360", "EC-370", "EC-380", "EC-390", "EC-400", "EC-420", "EC-430", "EC-440",
            "EC-450", "EC-460", "EC-470", "EC-480", "EC-490", "EC-500", "Tandy Organizer"
        });

        return tags.Distinct().OrderBy(t => t).ToList();
    }
}
